-- fix_qualidade_licoes_4.sql — gerado em 2026-07-08 (explicações mais completas)
-- Reescreve as 26 explicações mais curtas do banco com versões mais didáticas
-- (regra, exemplo embutido e erro comum do brasileiro). IDEMPOTENTE (valor fixo).
begin;
update licoes set explicacao = '''Used to + verbo'' descreve hábitos ou estados do passado que não acontecem mais: ''I used to smoke'' (eu fumava, mas parei). Só existe no passado — não diga ''I use to''. Na negativa e na pergunta o ''d'' desaparece: ''I didn''t use to like coffee'' / ''Did you use to play?''. Para hábitos atuais, use o presente simples com advérbio: ''I usually...''.' where id = '1c0965dc-38c1-4964-930e-d645cf6e154b';
update licoes set explicacao = 'O passado contínuo (was/were + verbo-ing) mostra uma ação que estava em andamento num momento do passado: ''I was studying at 8pm'' (eu estava estudando). É muito usado junto do passado simples, para uma ação que interrompe a outra: ''I was sleeping when the phone rang.''. Regra do par: I/he/she/it → was; you/we/they → were.' where id = 'be957048-6b36-4475-a573-c1011b98c982';
update licoes set explicacao = 'Para perguntar no presente, comece com ''Do'' (I/you/we/they) ou ''Does'' (he/she/it) e deixe o verbo na forma BASE: ''Does she work here?'' — o -s sai do verbo e vai para o Does. Respostas curtas: ''Yes, she does.'' / ''No, she doesn''t.''. Cuidado com o hábito do brasileiro de só subir a entonação (''She works?''): em inglês, a pergunta pede o Do/Does na frente.' where id = 'e0bffd11-d38f-4871-9bc0-3b6ad2c9497c';
update licoes set explicacao = 'Alguns verbos pedem -ing depois deles: enjoy, finish, avoid, mind, suggest (''I enjoy reading''). Outros pedem to + verbo: want, decide, hope, plan, need (''I want to read''). Não há lógica — é memorização por grupos. Duas âncoras que ajudam: depois de preposição é sempre -ing (''good at cooking'') e ''would like'' sempre pede to (''I''d like to go'').' where id = '72a76778-76cd-499f-adeb-217e14830a8d';
update licoes set explicacao = '''Should'' dá conselhos e sugestões — equivale ao nosso ''deveria'': ''You should sleep more.''. A forma é sempre should + verbo na base, sem to e sem -s: nunca ''should to go'' nem ''should goes''. Negativa: shouldn''t (''You shouldn''t smoke.''). Pergunta: ''Should I call her?'' (será que eu ligo?).' where id = '8eb9f948-4fca-4e61-a9c8-06128c32371f';
update licoes set explicacao = 'O presente contínuo também fala do FUTURO quando o plano já está combinado, com data ou hora marcada: ''I''m seeing the dentist tomorrow.'' (vou ao dentista amanhã). É o tempo favorito dos nativos para agenda: ''We''re having dinner with them on Friday.''. A palavra de tempo (tomorrow, next week, on Friday) é quem deixa claro que é futuro — não a esqueça.' where id = '71e01147-a586-4627-98ac-206c33a93bc1';
update licoes set explicacao = 'Três jeitos de falar de quantidade: ''a few'' = alguns, com contáveis (''a few friends''); ''a little'' = um pouco, com incontáveis (''a little water''); ''a lot of'' = muito(s), serve para os dois (''a lot of friends / a lot of time''). Pegadinha: sem o ''a'', o sentido fica negativo — ''few friends'' = quase nenhum amigo; ''little time'' = quase nenhum tempo.' where id = '9a69c805-db66-4014-af0b-64073cace52a';
update licoes set explicacao = 'O verbo ''have'' (ter) muda para ''has'' somente com he, she e it: ''She has a car.''. Com I, you, we e they, continua ''have'': ''I have two brothers.''. É a mesma lógica do -s da terceira pessoa. Na negativa com don''t/doesn''t, o verbo volta ao normal: ''She doesn''t have a car.'' (nunca ''doesn''t has'').' where id = 'd66423ff-a63c-48d6-a891-990b680da84f';
update licoes set explicacao = 'Quatro conectores que resolvem 90% das frases: ''and'' soma ideias (e), ''but'' contrasta (mas), ''because'' explica a causa (porque), ''so'' mostra a consequência (então/por isso). Compare: ''I was tired, SO I slept.'' (por isso dormi) e ''I slept BECAUSE I was tired.'' (porque estava cansado) — um aponta o resultado, o outro o motivo.' where id = 'd57d78f5-755f-44d3-a4cb-169657881472';
update licoes set explicacao = 'O future continuous (will be + verbo-ing) descreve uma ação que estará EM ANDAMENTO num momento específico do futuro: ''This time tomorrow I will be flying to Miami.'' (estarei voando). Compare com o will simples: ''I will fly'' = decisão/previsão; ''I will be flying'' = a cena acontecendo. Também rende perguntas educadas: ''Will you be using the car tonight?''.' where id = 'a64f5fbd-1514-412c-934b-415e512b6564';
update licoes set explicacao = '''Can'' expressa habilidade — o nosso ''saber/conseguir fazer'': ''I can swim.'' (sei nadar). A forma nunca muda: não existe ''cans'' nem ''to can'', e o verbo seguinte fica na base (''She can dance''). Negativa: can''t (''I can''t drive''). Pergunta: basta inverter — ''Can you help me?''. Can também pede e dá permissão: ''Can I come in?''.' where id = '5b1e91c9-5d00-4212-a2e0-9b97fdf32d55';
update licoes set explicacao = '''Will + verbo'' cobre três usos: decisão tomada NA HORA (''I''ll help you!''), previsão (''It will rain.'') e promessa (''I''ll call you.''). Contrações: I''ll, you''ll, she''ll; negativa: won''t (''I won''t tell anyone.''). Diferença chave para ''going to'': plano que já existia antes da conversa prefere going to; decisão de agora, will.' where id = 'bb79ca45-f835-4b48-bbb5-5d0b303088c5';
update licoes set explicacao = '''Going to'' = plano já decidido antes de falar: ''I''m going to travel in July.'' (já comprei a passagem). ''Will'' = decisão de agora (''I''ll have the pasta.'' — decidi olhando o cardápio) ou previsão/opinião (''I think it will rain.''). Previsão com evidência visível prefere going to: ''Look at those clouds — it''s going to rain!''.' where id = 'dbc2594c-2f52-40de-9592-3ab36b245081';
update licoes set explicacao = 'Muitos verbos andam SEMPRE com a mesma preposição — e ela nem sempre bate com o português: depend ON (depender DE), listen TO (escutar), wait FOR (esperar POR), look AT (olhar PARA), think ABOUT (pensar EM). Memorize o par como uma palavra só (''listen to music'', ''wait for the bus''): trocar a preposição soa errado na hora.' where id = 'a60e7ed6-8dc7-4a94-9971-e74c92b00f57';
update licoes set explicacao = 'Os verbos irregulares mudam de forma no passado sem regra: go → went, have → had, see → saw, eat → ate, buy → bought. Eles não recebem -ed — ''goed'' e ''buyed'' não existem. A boa notícia: os 20 mais comuns (be, go, do, say, get, make...) resolvem quase toda conversa. Na pergunta e na negativa com did, o verbo volta à base: ''Did you go?''.' where id = '84aacae4-1837-4b08-9dc6-3501493d45f2';
update licoes set explicacao = 'Kit de sobrevivência da viagem. No aeroporto: ''I have a reservation.'' (tenho reserva), ''Where is the gate?'' (onde fica o portão?), ''Is the flight on time?'' (o voo está no horário?). No hotel: ''I''d like to check in, please.'', ''What time is breakfast?'' e ''Could I have a late check-out?''. Decore como blocos prontos — é o inglês mais útil por metro quadrado.' where id = '591493c6-d679-4919-b9a4-26c4b8d3ebaa';
update licoes set explicacao = 'A segunda condicional imagina situações irreais ou improváveis: If + passado simples, would + verbo — ''If I had money, I would travel.'' (se eu tivesse, viajaria). O passado aqui NÃO é tempo: é sinal de hipótese, de faz de conta. Detalhe fino: com o verbo be, o formal usa were para todas as pessoas — ''If I were you...'' (se eu fosse você).' where id = '58c076bc-7b35-4558-95d9-4482b48ef619';
update licoes set explicacao = 'Quatro intensificadores que se confundem: ''so'' + adjetivo (''so tired'' — tão cansado); ''such'' + (a) + substantivo (''such a long day'' — um dia tão longo); ''too'' = demais, com ideia de problema (''too expensive'' — caro demais); ''enough'' = suficiente, e vem DEPOIS do adjetivo (''good enough'') mas ANTES do substantivo (''enough money'').' where id = '7e60bfdf-dc5b-49fa-8321-9e8fab6c5e20';
update licoes set explicacao = 'Os possessivos mostram de quem é algo e vêm antes do substantivo: my (meu), your (seu), his (dele), her (dela), its (de coisa/animal), our (nosso), their (deles). Diferente do português, não variam com a coisa possuída: ''my book, my books''. E atenção ao par que mais confunde: his = dele, her = dela — o gênero é do DONO, não do objeto.' where id = '11f1df5c-fe09-4f5d-9e97-8ec0342b48d0';
update licoes set explicacao = 'Pergunte ''What time is it?'' e responda com ''It is...'': hora cheia usa o''clock (''It''s eight o''clock.''); ''past'' = depois da hora (''ten past five'' = 5h10); ''to'' = para a próxima hora (''ten to five'' = 4h50). Meia hora: ''half past seven'' (7h30); quinze minutos: ''a quarter past/to''. Se enrolar, vale o modo digital: ''seven thirty''.' where id = '6a088abb-e9b0-42a8-8275-f69f435f70c2';
update licoes set explicacao = 'No present perfect, ''for'' e ''since'' marcam o tempo de jeitos diferentes: ''for'' + DURAÇÃO (''for two years'' — período de dois anos) e ''since'' + PONTO DE INÍCIO (''since 2022'', ''since Monday''). ''I have lived here for 10 years / since 2016.''. Truque: se a resposta é ''quanto tempo?'', use for; se é ''desde quando?'', use since.' where id = '68cb19c8-02aa-4cac-8a90-bde8e571c6c8';
update licoes set explicacao = 'A primeira condicional fala de situações reais e prováveis no futuro: If + presente simples, will + verbo — ''If it rains, we will stay home.''. O erro número 1 do brasileiro é pôr will nas duas partes: depois do IF vai PRESENTE (''if it rains'', nunca ''if it will rain''). As metades trocam de ordem sem mudar o sentido: ''We will stay home if it rains.''.' where id = 'bb7d0b07-0122-4d3d-9f88-d91d36eaccf3';
update licoes set explicacao = '''Should'' e ''ought to'' dão conselhos e recomendações — o nosso ''deveria'': ''You should see a doctor.'' / ''You ought to apologize.''. ''Should'' é muito mais comum; ''ought to'' soa um pouco mais formal e já carrega o to. Negativa e pergunta quase sempre com should: ''You shouldn''t work so much.'' / ''Should I tell her?''.' where id = '00cee458-ec31-4281-b07f-38cb42009b9c';
update licoes set explicacao = 'Vocabulário da cozinha: knife (faca), fork (garfo), spoon (colher), plate (prato), glass (copo), cup (xícara), pan (panela), bowl (tigela). Frases úteis: ''Can you pass me a fork?'' (me passa um garfo?) e ''The plates are on the table.''. Detalhe: copo é glass (de vidro) e xícara é cup — em inglês são palavras diferentes.' where id = '24f5ae22-ebe9-4821-937a-6ef05c3083b4';
update licoes set explicacao = 'Guia rápido de quantidade: ''some'' em afirmativas (''I have some money'') e ''any'' em negativas e perguntas (''I don''t have any.'' / ''Do you have any?''). Para ''muito'': much + incontável (''much time''), many + contável (''many friends'') e ''a lot of'' serve para os dois — e domina a fala do dia a dia. Em ofertas, some aparece na pergunta: ''Would you like some coffee?''.' where id = '840e5940-a34e-4d2f-9b2a-867b9a5213b8';
update licoes set explicacao = 'Para relatar uma ordem ou pedido, use tell/ask + pessoa + to + verbo: ''Close the door!'' → ''She told me to close the door.'' / ''He asked me to wait.''. Na negativa, o not vem antes do to: ''She told me NOT TO be late.''. Tell soa a ordem; ask, a pedido educado — escolha conforme o tom da fala original.' where id = '0965321c-f5c6-419e-820f-5d0b8bf37c2d';
commit;
