-- ============================================================================
-- Vonai - Lote 1 de licoes novas (20 licoes ineditas, nao duplicam as 220 do banco)
-- Como aplicar: Supabase -> SQL Editor -> cole tudo -> RUN. Seguro rodar 1x.
-- Resposta correta e sempre a 1a opcao (ans:0); o app embaralha as opcoes.
-- ============================================================================

insert into licoes (nivel, ordem, titulo, sub, icon, explicacao, dica, exemplos, questoes) values
('B1', 3001, $$Say x Tell$$, $$say something / tell someone$$, $$🗣️$$,
$$Use TELL quando há uma pessoa recebendo a informação (tell someone). Use SAY quando não menciona a pessoa (say something).$$,
$$Regra prática: 'tell me', 'say to me'. Nunca 'say me'.$$,
$j$[{"en": "She told me the truth.", "pt": "Ela me contou a verdade."}, {"en": "He said he was tired.", "pt": "Ele disse que estava cansado."}, {"en": "Tell me your name.", "pt": "Me diga seu nome."}]$j$::jsonb,
$j$[{"q": "Complete: She ___ me a secret.", "ctx": "", "opts": ["told", "said", "spoke", "talked"], "ans": 0, "exp": "TELL + pessoa (told me)."}, {"q": "Complete: He ___ that he was busy.", "ctx": "", "opts": ["said", "told", "told to", "say"], "ans": 0, "exp": "SAY sem pessoa (said that)."}, {"q": "Qual está errado?", "ctx": "", "opts": ["Say me the answer", "Tell me the answer", "Say hello", "Tell a story"], "ans": 0, "exp": "'Say me' não existe."}, {"q": "'Tell a lie' significa:", "ctx": "", "opts": ["contar uma mentira", "dizer a verdade", "fazer piada", "perguntar"], "ans": 0, "exp": "tell a lie = mentir."}, {"q": "Complete: Can you ___ me the time?", "ctx": "", "opts": ["tell", "say", "speak", "talk"], "ans": 0, "exp": "tell me the time."}, {"q": "Escolha o certo:", "ctx": "", "opts": ["He told us a joke.", "He said us a joke.", "He tell us a joke.", "He say a joke us."], "ans": 0, "exp": "tell + us (pessoa)."}]$j$::jsonb),

('B1', 3002, $$Lend x Borrow$$, $$emprestar x pegar emprestado$$, $$🔁$$,
$$LEND = emprestar (dar para alguém). BORROW = pegar emprestado (receber de alguém). O sentido é oposto!$$,
$$Lend TO / Borrow FROM. 'Lend me' = me empreste; 'borrow from you' = pegar de você.$$,
$j$[{"en": "Can you lend me your pen?", "pt": "Pode me emprestar sua caneta?"}, {"en": "I borrowed this book from the library.", "pt": "Peguei este livro emprestado da biblioteca."}, {"en": "He lent me some money.", "pt": "Ele me emprestou dinheiro."}]$j$::jsonb,
$j$[{"q": "'Me empreste' =", "ctx": "", "opts": ["Lend me", "Borrow me", "Lend from me", "Borrow to me"], "ans": 0, "exp": "lend me."}, {"q": "'Peguei emprestado do João' =", "ctx": "", "opts": ["I borrowed from João", "I lent from João", "I borrowed to João", "I lend João"], "ans": 0, "exp": "borrow from."}, {"q": "LEND significa:", "ctx": "", "opts": ["emprestar (dar)", "pegar emprestado", "comprar", "vender"], "ans": 0, "exp": "lend = dar emprestado."}, {"q": "Complete: Can I ___ your car?", "ctx": "", "opts": ["borrow", "lend", "lend to", "borrow to"], "ans": 0, "exp": "borrow (pegar emprestado)."}, {"q": "Complete: I'll ___ you my umbrella.", "ctx": "", "opts": ["lend", "borrow", "borrow from", "lend from"], "ans": 0, "exp": "lend you (te emprestar)."}, {"q": "Passado de 'lend':", "ctx": "", "opts": ["lent", "lended", "borrowed", "lend"], "ans": 0, "exp": "lend -> lent."}]$j$::jsonb),

('B1', 3003, $$Bring x Take$$, $$trazer x levar$$, $$👐$$,
$$BRING = trazer (para perto de quem fala). TAKE = levar (para longe de quem fala). Depende do ponto de referência.$$,
$$Bring here / Take there. 'Bring it to me' vs 'Take it to her'.$$,
$j$[{"en": "Bring me a glass of water, please.", "pt": "Me traga um copo de água."}, {"en": "Take your umbrella when you go out.", "pt": "Leve seu guarda-chuva ao sair."}, {"en": "I'll bring dessert to the party.", "pt": "Vou levar a sobremesa para a festa."}]$j$::jsonb,
$j$[{"q": "'Me traga o livro' =", "ctx": "", "opts": ["Bring me the book", "Take me the book", "Bring the book there", "Take here the book"], "ans": 0, "exp": "bring (para perto)."}, {"q": "'Leve isto para ela' =", "ctx": "", "opts": ["Take this to her", "Bring this to her", "Take here this", "Bring there this"], "ans": 0, "exp": "take (para longe)."}, {"q": "BRING indica movimento:", "ctx": "", "opts": ["em direção a quem fala", "para longe", "para cima", "nenhum"], "ans": 0, "exp": "trazer = para perto."}, {"q": "Complete: Don't forget to ___ your ID to the exam.", "ctx": "", "opts": ["take", "bring", "take to", "bring here"], "ans": 0, "exp": "take (levar para lá)."}, {"q": "Passado de 'bring':", "ctx": "", "opts": ["brought", "bringed", "brang", "brought to"], "ans": 0, "exp": "bring -> brought."}, {"q": "Passado de 'take':", "ctx": "", "opts": ["took", "taked", "taken", "take"], "ans": 0, "exp": "take -> took."}]$j$::jsonb),

('A2', 3004, $$Remind x Remember$$, $$lembrar x lembrar alguém$$, $$⏰$$,
$$REMEMBER = lembrar (de algo, você mesmo). REMIND = lembrar alguém / fazer recordar. 'Remind me' = me lembre.$$,
$$Remember = eu lembro. Remind someone = alguém/algo me faz lembrar.$$,
$j$[{"en": "I remember your face.", "pt": "Eu lembro do seu rosto."}, {"en": "Please remind me to call her.", "pt": "Por favor, me lembre de ligar para ela."}, {"en": "This song reminds me of summer.", "pt": "Essa música me lembra o verão."}]$j$::jsonb,
$j$[{"q": "'Me lembre de pagar' =", "ctx": "", "opts": ["Remind me to pay", "Remember me to pay", "Remind to pay me", "Remember to pay me"], "ans": 0, "exp": "remind me to."}, {"q": "'Eu lembro do nome dele' =", "ctx": "", "opts": ["I remember his name", "I remind his name", "I remember him name", "I remind of his name"], "ans": 0, "exp": "remember (eu lembro)."}, {"q": "REMIND precisa de:", "ctx": "", "opts": ["alguém para lembrar", "nada", "um objeto só", "um verbo no passado"], "ans": 0, "exp": "remind + someone."}, {"q": "Complete: You ___ me of my brother.", "ctx": "", "opts": ["remind", "remember", "reminds to", "remember to"], "ans": 0, "exp": "remind me of (me faz lembrar)."}, {"q": "Complete: Did you ___ to lock the door?", "ctx": "", "opts": ["remember", "remind", "reminded", "remember of"], "ans": 0, "exp": "remember to (lembrar de fazer)."}, {"q": "'Remind' significa:", "ctx": "", "opts": ["fazer alguém lembrar", "esquecer", "memorizar sozinho", "anotar"], "ans": 0, "exp": "lembrar alguém."}]$j$::jsonb),

('B2', 3005, $$Raise x Rise$$, $$levantar algo x subir$$, $$📈$$,
$$RAISE = levantar/aumentar ALGO (verbo transitivo, precisa de objeto). RISE = subir (sozinho, sem objeto). Raise is/was regular; rise-rose-risen.$$,
$$You raise your hand. The sun rises. Prices rise; companies raise prices.$$,
$j$[{"en": "Please raise your hand.", "pt": "Por favor, levante a mão."}, {"en": "The sun rises in the east.", "pt": "O sol nasce no leste."}, {"en": "They raised the prices last month.", "pt": "Eles aumentaram os preços mês passado."}]$j$::jsonb,
$j$[{"q": "Complete: Prices ___ every year.", "ctx": "", "opts": ["rise", "raise", "rises up", "are raised by"], "ans": 0, "exp": "rise (sobem sozinhos)."}, {"q": "Complete: The company will ___ salaries.", "ctx": "", "opts": ["raise", "rise", "rise up", "raised"], "ans": 0, "exp": "raise (aumentar algo)."}, {"q": "RAISE precisa de objeto?", "ctx": "", "opts": ["sim", "não", "às vezes não", "nunca"], "ans": 0, "exp": "raise é transitivo."}, {"q": "Passado de 'rise':", "ctx": "", "opts": ["rose", "rised", "raised", "risen"], "ans": 0, "exp": "rise -> rose -> risen."}, {"q": "'Levante a mão' =", "ctx": "", "opts": ["Raise your hand", "Rise your hand", "Raise up hand", "Rise the hand"], "ans": 0, "exp": "raise your hand."}, {"q": "'O sol nasce' =", "ctx": "", "opts": ["The sun rises", "The sun raises", "The sun rise up", "The sun is raised"], "ans": 0, "exp": "rise (sem objeto)."}]$j$::jsonb),

('B2', 3006, $$Lie x Lay$$, $$deitar x colocar (deitar algo)$$, $$🛏️$$,
$$LIE (lie-lay-lain) = deitar-se (sem objeto). LAY (lay-laid-laid) = colocar/deitar ALGO (com objeto). Confusão clássica até para nativos.$$,
$$I lie down (eu me deito). I lay the book on the table (coloco o livro). Cuidado: passado de 'lie' é 'lay'.$$,
$j$[{"en": "I lie down when I am tired.", "pt": "Eu me deito quando estou cansado."}, {"en": "Lay the baby on the bed.", "pt": "Deite o bebê na cama."}, {"en": "She laid the keys on the table.", "pt": "Ela colocou as chaves na mesa."}]$j$::jsonb,
$j$[{"q": "'Eu me deito' (agora) =", "ctx": "", "opts": ["I lie down", "I lay down", "I laid down", "I lain down"], "ans": 0, "exp": "lie down (deitar-se)."}, {"q": "'Coloque o livro aqui' =", "ctx": "", "opts": ["Lay the book here", "Lie the book here", "Lay down the book yourself", "Lie down the book"], "ans": 0, "exp": "lay + objeto."}, {"q": "LAY precisa de objeto?", "ctx": "", "opts": ["sim", "não", "nunca", "raramente"], "ans": 0, "exp": "lay é transitivo."}, {"q": "Passado de 'lay' (colocar):", "ctx": "", "opts": ["laid", "lay", "lain", "layed"], "ans": 0, "exp": "lay -> laid."}, {"q": "Passado de 'lie' (deitar):", "ctx": "", "opts": ["lay", "laid", "lied", "lain"], "ans": 0, "exp": "lie -> lay (confuso!)."}, {"q": "'Lie' (mentir) é diferente? Passado:", "ctx": "", "opts": ["lied", "lay", "laid", "lain"], "ans": 0, "exp": "lie(mentir) -> lied."}]$j$::jsonb),

('B1', 3007, $$Phrasal verbs com GET$$, $$get up, get on, get over$$, $$⬆️$$,
$$GET forma muitos phrasal verbs: get up (levantar), get on (embarcar/se dar bem), get over (superar), get by (se virar).$$,
$$get up = sair da cama; get over it = supere isso; get along with = se dar bem com.$$,
$j$[{"en": "I get up at 6 every day.", "pt": "Eu levanto às 6 todo dia."}, {"en": "She got over the flu quickly.", "pt": "Ela superou a gripe rápido."}, {"en": "They get along well.", "pt": "Eles se dão bem."}]$j$::jsonb,
$j$[{"q": "'Get up' =", "ctx": "", "opts": ["levantar da cama", "desistir", "entrar", "cair"], "ans": 0, "exp": "sair da cama."}, {"q": "'Get over something' =", "ctx": "", "opts": ["superar algo", "pegar algo", "cobrir", "repetir"], "ans": 0, "exp": "superar."}, {"q": "'Get on the bus' =", "ctx": "", "opts": ["embarcar no ônibus", "descer do ônibus", "perder o ônibus", "dirigir"], "ans": 0, "exp": "get on = embarcar."}, {"q": "'Get along with' =", "ctx": "", "opts": ["se dar bem com", "brigar com", "fugir de", "depender de"], "ans": 0, "exp": "se dar bem."}, {"q": "'Get by' =", "ctx": "", "opts": ["se virar/sobreviver", "passar por cima", "chegar cedo", "comprar"], "ans": 0, "exp": "se virar."}, {"q": "Complete: I can't ___ over it.", "ctx": "", "opts": ["get", "take", "put", "give"], "ans": 0, "exp": "get over."}]$j$::jsonb),

('B2', 3008, $$Phrasal verbs com TAKE$$, $$take off, take up, take after$$, $$✈️$$,
$$TAKE: take off (decolar/tirar roupa), take up (começar hobby), take after (puxar a/parecer), take over (assumir), take back (devolver/retirar o que disse).$$,
$$The plane takes off; I took up guitar; she takes after her mom.$$,
$j$[{"en": "The plane takes off at noon.", "pt": "O avião decola ao meio-dia."}, {"en": "I took up painting last year.", "pt": "Comecei a pintar ano passado."}, {"en": "He takes after his father.", "pt": "Ele puxou ao pai."}]$j$::jsonb,
$j$[{"q": "'Take off' (avião) =", "ctx": "", "opts": ["decolar", "pousar", "atrasar", "cancelar"], "ans": 0, "exp": "decolar."}, {"q": "'Take up a hobby' =", "ctx": "", "opts": ["começar um hobby", "largar", "odiar", "vender"], "ans": 0, "exp": "começar."}, {"q": "'Take after someone' =", "ctx": "", "opts": ["parecer com/puxar a", "seguir atrás", "cuidar", "imitar de propósito"], "ans": 0, "exp": "puxar a."}, {"q": "'Take over' =", "ctx": "", "opts": ["assumir o controle", "desistir", "viajar", "repetir"], "ans": 0, "exp": "assumir."}, {"q": "'Take off your coat' =", "ctx": "", "opts": ["tire o casaco", "vista o casaco", "decole", "guarde"], "ans": 0, "exp": "take off = tirar roupa."}, {"q": "'Take back' (o que disse) =", "ctx": "", "opts": ["retirar o que disse", "repetir", "gravar", "confirmar"], "ans": 0, "exp": "retirar."}]$j$::jsonb),

('B1', 3009, $$Phrasal verbs com PUT$$, $$put on, put off, put up with$$, $$🔘$$,
$$PUT: put on (vestir/ligar), put off (adiar), put up with (tolerar), put out (apagar fogo), put away (guardar).$$,
$$put on a jacket; put off the meeting; put up with noise; put out the fire.$$,
$j$[{"en": "Put on your shoes.", "pt": "Calce seus sapatos."}, {"en": "They put off the trip.", "pt": "Eles adiaram a viagem."}, {"en": "I can't put up with this noise.", "pt": "Não aguento esse barulho."}]$j$::jsonb,
$j$[{"q": "'Put on' (roupa) =", "ctx": "", "opts": ["vestir", "tirar", "lavar", "comprar"], "ans": 0, "exp": "vestir."}, {"q": "'Put off' =", "ctx": "", "opts": ["adiar", "ligar", "apagar", "guardar"], "ans": 0, "exp": "adiar."}, {"q": "'Put up with' =", "ctx": "", "opts": ["tolerar/aguentar", "construir", "levantar", "hospedar"], "ans": 0, "exp": "tolerar."}, {"q": "'Put out the fire' =", "ctx": "", "opts": ["apagar o fogo", "acender", "espalhar", "cobrir"], "ans": 0, "exp": "apagar."}, {"q": "'Put away' =", "ctx": "", "opts": ["guardar", "jogar fora", "adiar", "vestir"], "ans": 0, "exp": "guardar."}, {"q": "Complete: ___ on your coat, it's cold.", "ctx": "", "opts": ["Put", "Take", "Get", "Give"], "ans": 0, "exp": "put on."}]$j$::jsonb),

('B1', 3010, $$Phrasal verbs com LOOK$$, $$look for, look after, look up$$, $$🔎$$,
$$LOOK: look for (procurar), look after (cuidar de), look up (procurar informação/melhorar), look forward to (ansiar por), look up to (admirar).$$,
$$look for keys; look after a child; look up a word; look forward to the trip.$$,
$j$[{"en": "I'm looking for my keys.", "pt": "Estou procurando minhas chaves."}, {"en": "She looks after her grandmother.", "pt": "Ela cuida da avó."}, {"en": "Look up the word in the dictionary.", "pt": "Procure a palavra no dicionário."}]$j$::jsonb,
$j$[{"q": "'Look for' =", "ctx": "", "opts": ["procurar", "olhar para", "cuidar", "admirar"], "ans": 0, "exp": "procurar."}, {"q": "'Look after' =", "ctx": "", "opts": ["cuidar de", "procurar", "olhar depois", "copiar"], "ans": 0, "exp": "cuidar."}, {"q": "'Look up' (palavra) =", "ctx": "", "opts": ["consultar/procurar", "olhar para cima só", "desistir", "apagar"], "ans": 0, "exp": "consultar."}, {"q": "'Look forward to' =", "ctx": "", "opts": ["ansiar por", "olhar para frente só", "evitar", "esquecer"], "ans": 0, "exp": "ansiar por."}, {"q": "'Look up to someone' =", "ctx": "", "opts": ["admirar", "procurar", "cuidar", "ligar"], "ans": 0, "exp": "admirar."}, {"q": "Complete: I'm looking ___ my phone.", "ctx": "", "opts": ["for", "after", "up", "forward"], "ans": 0, "exp": "look for."}]$j$::jsonb),

('B2', 3011, $$Phrasal verbs com TURN$$, $$turn on, turn down, turn up$$, $$🔀$$,
$$TURN: turn on/off (ligar/desligar), turn up/down (aumentar/diminuir ou aparecer/recusar), turn into (transformar-se), turn out (acabar sendo).$$,
$$turn on the TV; turn down the volume; he turned up late; it turned out fine.$$,
$j$[{"en": "Turn on the lights.", "pt": "Acenda as luzes."}, {"en": "Please turn down the music.", "pt": "Por favor, abaixe a música."}, {"en": "It turned out to be true.", "pt": "Acabou sendo verdade."}]$j$::jsonb,
$j$[{"q": "'Turn on' =", "ctx": "", "opts": ["ligar", "desligar", "virar", "recusar"], "ans": 0, "exp": "ligar."}, {"q": "'Turn down' (volume) =", "ctx": "", "opts": ["diminuir", "aumentar", "ligar", "gravar"], "ans": 0, "exp": "diminuir."}, {"q": "'Turn down an offer' =", "ctx": "", "opts": ["recusar", "aceitar", "adiar", "assinar"], "ans": 0, "exp": "recusar."}, {"q": "'Turn up' (pessoa) =", "ctx": "", "opts": ["aparecer/chegar", "sumir", "atrasar de novo", "recusar"], "ans": 0, "exp": "aparecer."}, {"q": "'Turn out' =", "ctx": "", "opts": ["acabar sendo", "desligar", "virar", "cancelar"], "ans": 0, "exp": "acabar sendo."}, {"q": "'Turn into' =", "ctx": "", "opts": ["transformar-se em", "entrar", "recusar", "aumentar"], "ans": 0, "exp": "transformar-se."}]$j$::jsonb),

('B2', 3012, $$Idioms com animais$$, $$hold your horses, cold turkey$$, $$🐴$$,
$$Muitos idioms usam animais. Ex.: hold your horses (calma), let the cat out of the bag (revelar segredo), a piece of cake (fácil).$$,
$$São expressões fixas — o sentido não é literal.$$,
$j$[{"en": "Hold your horses, we have time.", "pt": "Calma, temos tempo."}, {"en": "He let the cat out of the bag.", "pt": "Ele revelou o segredo."}, {"en": "The exam was a piece of cake.", "pt": "A prova foi moleza."}]$j$::jsonb,
$j$[{"q": "'Hold your horses' =", "ctx": "", "opts": ["tenha calma", "corra", "segure firme", "monte"], "ans": 0, "exp": "calma."}, {"q": "'Let the cat out of the bag' =", "ctx": "", "opts": ["revelar um segredo", "perder o gato", "mentir", "fugir"], "ans": 0, "exp": "revelar segredo."}, {"q": "'A piece of cake' =", "ctx": "", "opts": ["muito fácil", "um doce", "uma parte", "difícil"], "ans": 0, "exp": "fácil."}, {"q": "'Kill two birds with one stone' =", "ctx": "", "opts": ["resolver duas coisas de uma vez", "ser cruel", "falhar", "desistir"], "ans": 0, "exp": "dois em um."}, {"q": "'When pigs fly' =", "ctx": "", "opts": ["nunca (impossível)", "logo", "sempre", "em breve"], "ans": 0, "exp": "nunca."}, {"q": "'The elephant in the room' =", "ctx": "", "opts": ["problema óbvio ignorado", "animal grande", "segredo pequeno", "piada"], "ans": 0, "exp": "problema óbvio."}]$j$::jsonb),

('B2', 3013, $$Idioms com cores$$, $$feeling blue, once in a blue moon$$, $$🎨$$,
$$Cores aparecem em muitos idioms: feel blue (triste), green with envy (com inveja), once in a blue moon (raramente), red tape (burocracia).$$,
$$Sentido figurado — não é sobre a cor real.$$,
$j$[{"en": "I'm feeling blue today.", "pt": "Estou meio pra baixo hoje."}, {"en": "She was green with envy.", "pt": "Ela estava morrendo de inveja."}, {"en": "We meet once in a blue moon.", "pt": "A gente se vê muito raramente."}]$j$::jsonb,
$j$[{"q": "'Feeling blue' =", "ctx": "", "opts": ["triste", "feliz", "com frio", "com raiva"], "ans": 0, "exp": "triste."}, {"q": "'Green with envy' =", "ctx": "", "opts": ["morrendo de inveja", "doente", "novato", "com nojo"], "ans": 0, "exp": "inveja."}, {"q": "'Once in a blue moon' =", "ctx": "", "opts": ["raramente", "sempre", "nunca", "à noite"], "ans": 0, "exp": "raramente."}, {"q": "'Red tape' =", "ctx": "", "opts": ["burocracia", "fita vermelha", "perigo", "festa"], "ans": 0, "exp": "burocracia."}, {"q": "'Caught red-handed' =", "ctx": "", "opts": ["pego no flagrante", "com as mãos frias", "envergonhado", "corado"], "ans": 0, "exp": "flagrante."}, {"q": "'A grey area' =", "ctx": "", "opts": ["área indefinida/duvidosa", "lugar escuro", "zona proibida", "céu nublado"], "ans": 0, "exp": "indefinido."}]$j$::jsonb),

('C1', 3014, $$Idioms com partes do corpo$$, $$cost an arm and a leg$$, $$🦵$$,
$$Idioms com o corpo são comuns: cost an arm and a leg (caríssimo), pull someone's leg (brincar), get cold feet (amarelar), off the top of my head (de cabeça).$$,
$$Fixos e figurados — memorize como blocos.$$,
$j$[{"en": "That car cost an arm and a leg.", "pt": "Aquele carro custou os olhos da cara."}, {"en": "I'm just pulling your leg.", "pt": "Só estou brincando com você."}, {"en": "He got cold feet before the wedding.", "pt": "Ele amarelou antes do casamento."}]$j$::jsonb,
$j$[{"q": "'Cost an arm and a leg' =", "ctx": "", "opts": ["ser caríssimo", "ser barato", "doer", "valer a pena"], "ans": 0, "exp": "caríssimo."}, {"q": "'Pull someone's leg' =", "ctx": "", "opts": ["brincar/zoar", "machucar", "ajudar", "puxar"], "ans": 0, "exp": "brincar."}, {"q": "'Get cold feet' =", "ctx": "", "opts": ["amarelar/hesitar", "ficar com frio", "correr", "decidir"], "ans": 0, "exp": "hesitar."}, {"q": "'Off the top of my head' =", "ctx": "", "opts": ["de cabeça (sem consultar)", "com dor de cabeça", "do topo", "de cor decorado"], "ans": 0, "exp": "de cabeça."}, {"q": "'Keep an eye on' =", "ctx": "", "opts": ["ficar de olho em", "fechar os olhos", "piscar", "procurar"], "ans": 0, "exp": "vigiar."}, {"q": "'A pain in the neck' =", "ctx": "", "opts": ["algo/alguém chato", "dor real", "doença", "cansaço"], "ans": 0, "exp": "chato."}]$j$::jsonb),

('B2', 3015, $$Collocations com MAKE$$, $$make a decision, make sense$$, $$🧩$$,
$$MAKE combina com certas palavras: make a decision, make a mistake, make progress, make sense, make an effort, make money.$$,
$$São combinações fixas — 'do a decision' está errado.$$,
$j$[{"en": "I need to make a decision.", "pt": "Preciso tomar uma decisão."}, {"en": "That doesn't make sense.", "pt": "Isso não faz sentido."}, {"en": "You made a lot of progress.", "pt": "Você fez muito progresso."}]$j$::jsonb,
$j$[{"q": "Correto:", "ctx": "", "opts": ["make a decision", "do a decision", "take a decision", "have a decision"], "ans": 0, "exp": "make a decision."}, {"q": "Correto:", "ctx": "", "opts": ["make a mistake", "do a mistake", "have a mistake", "take a mistake"], "ans": 0, "exp": "make a mistake."}, {"q": "'Fazer sentido' =", "ctx": "", "opts": ["make sense", "do sense", "take sense", "have sense"], "ans": 0, "exp": "make sense."}, {"q": "'Fazer um esforço' =", "ctx": "", "opts": ["make an effort", "do an effort", "take an effort", "have effort"], "ans": 0, "exp": "make an effort."}, {"q": "'Ganhar dinheiro' =", "ctx": "", "opts": ["make money", "do money", "win money", "take money"], "ans": 0, "exp": "make money."}, {"q": "'Fazer progresso' =", "ctx": "", "opts": ["make progress", "do progress", "take progress", "give progress"], "ans": 0, "exp": "make progress."}]$j$::jsonb),

('B2', 3016, $$Collocations com HAVE$$, $$have a shower, have fun$$, $$🛁$$,
$$HAVE combina com atividades e experiências: have breakfast, have a shower, have fun, have a break, have a look, have a good time.$$,
$$'Have a shower' (UK) / 'take a shower' (US) — ambos aceitos.$$,
$j$[{"en": "Let's have a break.", "pt": "Vamos fazer uma pausa."}, {"en": "Have a look at this.", "pt": "Dá uma olhada nisto."}, {"en": "We had a great time.", "pt": "Nós nos divertimos muito."}]$j$::jsonb,
$j$[{"q": "'Tomar café da manhã' =", "ctx": "", "opts": ["have breakfast", "do breakfast", "make breakfast only", "take breakfast"], "ans": 0, "exp": "have breakfast."}, {"q": "'Dar uma olhada' =", "ctx": "", "opts": ["have a look", "do a look", "make a look", "see a look"], "ans": 0, "exp": "have a look."}, {"q": "'Se divertir' =", "ctx": "", "opts": ["have fun", "do fun", "make fun", "take fun"], "ans": 0, "exp": "have fun (make fun of = zoar)."}, {"q": "'Fazer uma pausa' =", "ctx": "", "opts": ["have a break", "do a break", "take break only", "give a break"], "ans": 0, "exp": "have a break."}, {"q": "'Tomar banho' (UK) =", "ctx": "", "opts": ["have a shower", "do a shower", "make a shower", "give a shower"], "ans": 0, "exp": "have a shower."}, {"q": "'Ter um bom tempo/curtir' =", "ctx": "", "opts": ["have a good time", "do a good time", "make good time only", "take a good time"], "ans": 0, "exp": "have a good time."}]$j$::jsonb),

('A2', 3017, $$Vocabulário: música e instrumentos$$, $$guitar, drums, lyrics$$, $$🎸$$,
$$Vocabulário de música: song (música), lyrics (letra), band (banda), guitar (violão), drums (bateria), singer (cantor), tune (melodia).$$,
$$'Play the guitar' — instrumentos levam 'the'.$$,
$j$[{"en": "I play the guitar.", "pt": "Eu toco violão."}, {"en": "I love the lyrics of this song.", "pt": "Amo a letra desta música."}, {"en": "She is the lead singer.", "pt": "Ela é a vocalista."}]$j$::jsonb,
$j$[{"q": "'Letra da música' =", "ctx": "", "opts": ["lyrics", "tune", "band", "stage"], "ans": 0, "exp": "lyrics."}, {"q": "'Bateria' =", "ctx": "", "opts": ["drums", "guitar", "piano", "violin"], "ans": 0, "exp": "drums."}, {"q": "'Cantor(a)' =", "ctx": "", "opts": ["singer", "player", "dancer", "writer"], "ans": 0, "exp": "singer."}, {"q": "'Banda' =", "ctx": "", "opts": ["band", "team", "group work", "crowd"], "ans": 0, "exp": "band."}, {"q": "Complete: I play ___ piano.", "ctx": "", "opts": ["the", "a", "an", "no article"], "ans": 0, "exp": "play the piano."}, {"q": "'Melodia' =", "ctx": "", "opts": ["tune", "noise", "word", "beat only"], "ans": 0, "exp": "tune."}]$j$::jsonb),

('B1', 3018, $$Vocabulário: tecnologia e redes sociais$$, $$post, follow, download$$, $$📱$$,
$$Vocabulário digital: post (postar), share (compartilhar), follow (seguir), like (curtir), download/upload, password (senha), screen (tela), app (aplicativo).$$,
$$Muitos viraram verbos: 'to post', 'to like', 'to follow'.$$,
$j$[{"en": "She posted a photo online.", "pt": "Ela postou uma foto online."}, {"en": "Don't forget your password.", "pt": "Não esqueça sua senha."}, {"en": "I follow her on social media.", "pt": "Eu a sigo nas redes sociais."}]$j$::jsonb,
$j$[{"q": "'Postar' =", "ctx": "", "opts": ["post", "paste", "send only", "print"], "ans": 0, "exp": "post."}, {"q": "'Compartilhar' =", "ctx": "", "opts": ["share", "split", "divide", "cut"], "ans": 0, "exp": "share."}, {"q": "'Senha' =", "ctx": "", "opts": ["password", "passport", "key word", "secret door"], "ans": 0, "exp": "password."}, {"q": "'Baixar' =", "ctx": "", "opts": ["download", "upload", "unload", "load off"], "ans": 0, "exp": "download."}, {"q": "'Seguir (alguém)' =", "ctx": "", "opts": ["follow", "chase", "look after", "go after"], "ans": 0, "exp": "follow."}, {"q": "'Tela' =", "ctx": "", "opts": ["screen", "board", "glass", "window only"], "ans": 0, "exp": "screen."}]$j$::jsonb),

('C2', 3019, $$Nominalização$$, $$turn verbs into nouns$$, $$🏛️$$,
$$Nominalização é transformar verbos/adjetivos em substantivos (decide -> decision; fail -> failure). É a marca do inglês formal e acadêmico, tornando o texto mais denso e impessoal.$$,
$$Compare: 'We decided quickly' (informal) x 'The decision was quick' (formal/acadêmico).$$,
$j$[{"en": "The implementation of the plan failed.", "pt": "A implementação do plano fracassou."}, {"en": "Her analysis was thorough.", "pt": "A análise dela foi minuciosa."}, {"en": "The reduction in costs helped.", "pt": "A redução de custos ajudou."}]$j$::jsonb,
$j$[{"q": "Nominalização de 'decide':", "ctx": "", "opts": ["decision", "deciding", "decided", "decisive"], "ans": 0, "exp": "decide -> decision."}, {"q": "Nominalização de 'fail':", "ctx": "", "opts": ["failure", "failing", "failed", "fail off"], "ans": 0, "exp": "fail -> failure."}, {"q": "Nominalização de 'analyse':", "ctx": "", "opts": ["analysis", "analysing", "analysed", "analytic"], "ans": 0, "exp": "analyse -> analysis."}, {"q": "Nominalização torna o texto mais:", "ctx": "", "opts": ["formal e impessoal", "informal", "curto sempre", "emocional"], "ans": 0, "exp": "formal/acadêmico."}, {"q": "'grow' vira:", "ctx": "", "opts": ["growth", "growing", "grew", "grown"], "ans": 0, "exp": "grow -> growth."}, {"q": "Versão nominalizada de 'We reduced costs':", "ctx": "", "opts": ["The reduction of costs", "We reducing costs", "Cost we reduce", "Reduce of costs"], "ans": 0, "exp": "reduction."}]$j$::jsonb),

('C2', 3020, $$Understatement e ironia britânica$$, $$'not bad' = ótimo$$, $$🇬🇧$$,
$$No inglês britânico, understatement suaviza de propósito: 'not bad' pode significar excelente; 'a bit of a problem' pode ser um desastre. Entender o tom evita mal-entendidos.$$,
$$Muitas vezes o significado real é mais forte do que as palavras sugerem.$$,
$j$[{"en": "'It's not bad at all.' (means: it's great)", "pt": "'Nada mal.' (significa: ótimo)"}, {"en": "'We have a slight problem.' (means: big trouble)", "pt": "'Temos um probleminha.' (significa: encrenca séria)"}, {"en": "'I'm not entirely happy.' (means: very upset)", "pt": "'Não estou totalmente feliz.' (significa: muito chateado)"}]$j$::jsonb,
$j$[{"q": "'Not bad' (understatement) costuma significar:", "ctx": "", "opts": ["muito bom", "péssimo", "normal", "estranho"], "ans": 0, "exp": "understatement positivo."}, {"q": "'A slight problem' pode na verdade ser:", "ctx": "", "opts": ["um problemão", "nada", "uma dúvida", "uma piada"], "ans": 0, "exp": "suavização."}, {"q": "Understatement serve para:", "ctx": "", "opts": ["suavizar / soar educado", "exagerar", "ofender", "confundir de propósito"], "ans": 0, "exp": "suavizar."}, {"q": "'I'm not entirely convinced' =", "ctx": "", "opts": ["discordo bastante", "concordo 100%", "não entendi", "estou animado"], "ans": 0, "exp": "discordância educada."}, {"q": "Isso é mais típico do inglês:", "ctx": "", "opts": ["britânico", "americano informal", "técnico", "antigo"], "ans": 0, "exp": "britânico."}, {"q": "Ler understatement exige atenção ao:", "ctx": "", "opts": ["tom e contexto", "dicionário só", "sotaque", "tempo verbal"], "ans": 0, "exp": "tom/contexto."}]$j$::jsonb);
