-- ============================================================================
-- Vonai - Lote C2 avancado (30 licoes ineditas, ordem 4031-4060)
-- Cole no Supabase -> SQL Editor -> RUN. Seguro rodar mais de uma vez.
-- Resposta correta e sempre a 1a opcao (ans:0); o app embaralha as opcoes.
-- ============================================================================
begin;
delete from licoes where ordem between 4031 and 4060;

insert into licoes (nivel, ordem, titulo, sub, icon, explicacao, dica, exemplos, questoes) values

('C2', 4031, $$Idioms com partes do corpo$$, $$pull someone's leg$$, $$🦵$$,
$$Muitos idioms usam o corpo: pull someone's leg (brincar/zoar), cost an arm and a leg (custar caro), keep an eye on (vigiar), get cold feet (amarelar), by the skin of your teeth (por pouco).$$,
$$Nao sao literais: 'pull your leg' e brincadeira, nao puxar a perna.$$,
$j$[{"en": "Are you pulling my leg?", "pt": "Voce esta me zoando?"}, {"en": "It cost an arm and a leg.", "pt": "Custou os olhos da cara."}, {"en": "He got cold feet before the wedding.", "pt": "Ele amarelou antes do casamento."}]$j$::jsonb,
$j$[{"q": "'Pull someone's leg' =", "ctx": "", "opts": ["brincar/zoar", "puxar a perna", "ajudar", "correr"], "ans": 0, "exp": "Fazer graca."}, {"q": "'Cost an arm and a leg' =", "ctx": "", "opts": ["custar muito caro", "ser barato", "machucar", "ser gratis"], "ans": 0, "exp": "Muito caro."}, {"q": "'Keep an eye on' =", "ctx": "", "opts": ["vigiar/ficar de olho", "fechar o olho", "piscar", "ignorar"], "ans": 0, "exp": "Vigiar."}, {"q": "'Get cold feet' =", "ctx": "", "opts": ["ficar com medo/amarelar", "sentir frio", "correr", "dormir"], "ans": 0, "exp": "Perder a coragem."}, {"q": "'By the skin of your teeth' =", "ctx": "", "opts": ["por muito pouco", "com forca", "com folga", "com sorte total"], "ans": 0, "exp": "Escapar por pouco."}, {"q": "Idioms de corpo sao:", "ctx": "", "opts": ["figurados, nao literais", "sempre literais", "gramatica", "girias erradas"], "ans": 0, "exp": "Sentido figurado."}]$j$::jsonb),

('C2', 4032, $$Idioms com animais$$, $$let the cat out of the bag$$, $$🐱$$,
$$Animais em idioms: let the cat out of the bag (revelar segredo), a dark horse (surpresa/talento oculto), hold your horses (calma), the elephant in the room (assunto obvio ignorado), kill two birds with one stone (dois em um).$$,
$$'Let the cat out of the bag' = contar sem querer.$$,
$j$[{"en": "He let the cat out of the bag.", "pt": "Ele deixou o segredo escapar."}, {"en": "Let's not ignore the elephant in the room.", "pt": "Nao vamos ignorar o obvio."}, {"en": "We killed two birds with one stone.", "pt": "Matamos dois coelhos com uma cajadada."}]$j$::jsonb,
$j$[{"q": "'Let the cat out of the bag' =", "ctx": "", "opts": ["revelar um segredo", "soltar o gato", "mentir", "esconder"], "ans": 0, "exp": "Contar sem querer."}, {"q": "'The elephant in the room' =", "ctx": "", "opts": ["assunto obvio que ninguem toca", "animal grande", "sala apertada", "problema pequeno"], "ans": 0, "exp": "Tema evitado."}, {"q": "'Hold your horses' =", "ctx": "", "opts": ["tenha calma/espere", "corra", "segure cavalos", "decida ja"], "ans": 0, "exp": "Calma."}, {"q": "'A dark horse' =", "ctx": "", "opts": ["alguem com talento oculto", "cavalo preto", "vilao", "azar"], "ans": 0, "exp": "Surpresa positiva."}, {"q": "'Kill two birds with one stone' =", "ctx": "", "opts": ["resolver duas coisas de uma vez", "ser cruel", "falhar", "repetir"], "ans": 0, "exp": "Dois em um."}, {"q": "Esses idioms devem ser lidos:", "ctx": "", "opts": ["no sentido figurado", "literalmente", "como regras", "como girias erradas"], "ans": 0, "exp": "Figurado."}]$j$::jsonb),

('C2', 4033, $$Idioms com clima$$, $$under the weather$$, $$🌦️$$,
$$Clima vira sentimento: under the weather (indisposto), a storm in a teacup (tempestade em copo dagua), take a rain check (fica pra proxima), on cloud nine (nas nuvens/muito feliz), steal someone's thunder (roubar a cena).$$,
$$'Under the weather' = meio doente, nao sobre o tempo.$$,
$j$[{"en": "I'm feeling under the weather.", "pt": "Estou meio indisposto."}, {"en": "Can I take a rain check?", "pt": "Podemos deixar para outra hora?"}, {"en": "She was on cloud nine.", "pt": "Ela estava nas nuvens."}]$j$::jsonb,
$j$[{"q": "'Under the weather' =", "ctx": "", "opts": ["indisposto/meio doente", "com frio", "molhado", "feliz"], "ans": 0, "exp": "Adoentado."}, {"q": "'Take a rain check' =", "ctx": "", "opts": ["adiar para outra vez", "checar a chuva", "cancelar de vez", "aceitar"], "ans": 0, "exp": "Fica pra proxima."}, {"q": "'On cloud nine' =", "ctx": "", "opts": ["extremamente feliz", "confuso", "no aviao", "triste"], "ans": 0, "exp": "Nas nuvens."}, {"q": "'A storm in a teacup' =", "ctx": "", "opts": ["exagero por algo pequeno", "tempestade real", "cha quente", "problema serio"], "ans": 0, "exp": "Tempestade em copo dagua."}, {"q": "'Steal someone's thunder' =", "ctx": "", "opts": ["roubar a atencao/o merito", "roubar dinheiro", "trovao", "assustar"], "ans": 0, "exp": "Roubar a cena."}, {"q": "Idioms de clima descrevem:", "ctx": "", "opts": ["sentimentos/situacoes", "so o tempo", "gramatica", "numeros"], "ans": 0, "exp": "Sentido figurado."}]$j$::jsonb),

('C2', 4034, $$Sinonimos de BIG$$, $$large / huge / vast / immense$$, $$📏$$,
$$'Big' tem nuances: large (grande, neutro/formal), huge (enorme), vast (vasto - areas/quantidades), enormous/immense (imenso), gigantic (gigantesco). A escolha muda a intensidade e o registro.$$,
$$'Vast' combina com espaco/quantia (a vast desert), nao com pessoas.$$,
$j$[{"en": "A vast desert stretched ahead.", "pt": "Um vasto deserto se estendia."}, {"en": "There was a huge crowd.", "pt": "Havia uma multidao enorme."}, {"en": "The costs were immense.", "pt": "Os custos foram imensos."}]$j$::jsonb,
$j$[{"q": "Mais forte que 'big':", "ctx": "", "opts": ["enormous", "little", "small", "tiny"], "ans": 0, "exp": "enormous = muito grande."}, {"q": "'Vast' combina melhor com:", "ctx": "", "opts": ["a vast area", "a vast baby", "a vast smile", "a vast pen"], "ans": 0, "exp": "Areas/quantidades."}, {"q": "Mais formal/neutro que 'big':", "ctx": "", "opts": ["large", "huge", "gigantic", "massive"], "ans": 0, "exp": "large = formal."}, {"q": "'Immense' significa:", "ctx": "", "opts": ["imenso", "minusculo", "medio", "vazio"], "ans": 0, "exp": "Muito grande."}, {"q": "Escolher o sinonimo certo afeta:", "ctx": "", "opts": ["intensidade e registro", "so a pronuncia", "o tempo verbal", "a ordem"], "ans": 0, "exp": "Nuance."}, {"q": "Exagero coloquial de 'big':", "ctx": "", "opts": ["massive", "large", "sizeable", "considerable"], "ans": 0, "exp": "massive = informal enfatico."}]$j$::jsonb),

('C2', 4035, $$Sinonimos de HAPPY$$, $$glad / delighted / thrilled$$, $$😄$$,
$$Graus de felicidade: glad (contente, leve), pleased (satisfeito, formal), delighted (muito feliz, educado), thrilled (empolgadissimo), content (tranquilo/satisfeito), overjoyed (radiante).$$,
$$'Delighted' e educado e forte: 'I'd be delighted to help'.$$,
$j$[{"en": "I'm delighted to meet you.", "pt": "Estou encantado em conhece-lo."}, {"en": "She was thrilled with the news.", "pt": "Ela ficou empolgadissima com a noticia."}, {"en": "He felt content with life.", "pt": "Ele se sentia satisfeito com a vida."}]$j$::jsonb,
$j$[{"q": "Muito feliz e educado:", "ctx": "", "opts": ["delighted", "glad", "okay", "fine"], "ans": 0, "exp": "delighted."}, {"q": "Empolgadissimo:", "ctx": "", "opts": ["thrilled", "content", "pleased", "glad"], "ans": 0, "exp": "thrilled."}, {"q": "Contente de forma leve:", "ctx": "", "opts": ["glad", "overjoyed", "thrilled", "ecstatic"], "ans": 0, "exp": "glad = leve."}, {"q": "'Content' sugere:", "ctx": "", "opts": ["satisfacao tranquila", "euforia", "raiva", "medo"], "ans": 0, "exp": "Satisfeito/em paz."}, {"q": "Mais formal que 'happy':", "ctx": "", "opts": ["pleased", "stoked", "chuffed", "over the moon"], "ans": 0, "exp": "pleased = formal."}, {"q": "'Over the moon' e:", "ctx": "", "opts": ["felicissimo (informal)", "triste", "cansado", "neutro"], "ans": 0, "exp": "Muito feliz, coloquial."}]$j$::jsonb),

('C2', 4036, $$Sinonimos de ANGRY$$, $$annoyed / furious / irritated$$, $$😠$$,
$$Graus de raiva: annoyed/irritated (irritado, leve), cross (chateado, UK), mad (bravo, US informal), furious (furioso), livid/enraged (fora de si). A intensidade importa muito no tom.$$,
$$'Furious' e bem mais forte que 'annoyed'.$$,
$j$[{"en": "I'm a bit annoyed.", "pt": "Estou um pouco irritado."}, {"en": "She was furious about the delay.", "pt": "Ela ficou furiosa com o atraso."}, {"en": "He was absolutely livid.", "pt": "Ele estava fora de si."}]$j$::jsonb,
$j$[{"q": "Raiva leve:", "ctx": "", "opts": ["annoyed", "furious", "livid", "enraged"], "ans": 0, "exp": "annoyed = leve."}, {"q": "Raiva forte:", "ctx": "", "opts": ["furious", "annoyed", "irritated", "cross"], "ans": 0, "exp": "furious = forte."}, {"q": "'Livid' significa:", "ctx": "", "opts": ["furioso ao extremo", "levemente chateado", "feliz", "cansado"], "ans": 0, "exp": "Muito furioso."}, {"q": "'Cross' (UK) e:", "ctx": "", "opts": ["chateado (leve/medio)", "furioso", "cruzado", "feliz"], "ans": 0, "exp": "Chateado."}, {"q": "Escolher o grau certo transmite:", "ctx": "", "opts": ["a intensidade real", "o tempo verbal", "o numero", "o genero"], "ans": 0, "exp": "Nuance de intensidade."}, {"q": "Mais intenso que 'annoyed':", "ctx": "", "opts": ["enraged", "slightly bothered", "a bit off", "meh"], "ans": 0, "exp": "enraged = extremo."}]$j$::jsonb),

('C2', 4037, $$Conotacao$$, $$slim x skinny x thin$$, $$🎭$$,
$$Palavras parecidas carregam julgamento. Magro: slim (positivo), thin (neutro), skinny (negativo, magro demais). Curioso: curious (positivo) x nosy (bisbilhoteiro). Economico: thrifty (positivo) x stingy (pao-duro).$$,
$$A conotacao revela sua opiniao: 'slim' elogia, 'skinny' critica.$$,
$j$[{"en": "She looks slim and healthy.", "pt": "Ela parece magra e saudavel."}, {"en": "He's too skinny.", "pt": "Ele esta magro demais."}, {"en": "My neighbor is very nosy.", "pt": "Meu vizinho e muito bisbilhoteiro."}]$j$::jsonb,
$j$[{"q": "'Magro' com conotacao positiva:", "ctx": "", "opts": ["slim", "skinny", "bony", "scrawny"], "ans": 0, "exp": "slim = elogio."}, {"q": "'Magro demais' (negativo):", "ctx": "", "opts": ["skinny", "slim", "slender", "trim"], "ans": 0, "exp": "skinny = critica."}, {"q": "'Curioso' negativo:", "ctx": "", "opts": ["nosy", "curious", "interested", "keen"], "ans": 0, "exp": "nosy = bisbilhoteiro."}, {"q": "'Economico' positivo:", "ctx": "", "opts": ["thrifty", "stingy", "mean", "tight"], "ans": 0, "exp": "thrifty = elogio."}, {"q": "'Stingy' significa:", "ctx": "", "opts": ["pao-duro (negativo)", "generoso", "economico elogioso", "rico"], "ans": 0, "exp": "Conotacao negativa."}, {"q": "Conotacao e:", "ctx": "", "opts": ["a carga emocional da palavra", "o som", "o plural", "o tempo"], "ans": 0, "exp": "Julgamento embutido."}]$j$::jsonb),

('C2', 4038, $$Registro: formal x informal$$, $$purchase x buy$$, $$🎩$$,
$$Muitas ideias tem versao formal e informal. buy/purchase, ask/enquire, help/assist, get/obtain, need/require, start/commence, end/terminate, about/regarding. O formal soa profissional; o informal, natural.$$,
$$Em documentos/negocios use o formal; entre amigos, o informal.$$,
$j$[{"en": "You may purchase tickets online.", "pt": "Voce pode comprar ingressos online."}, {"en": "Please do not hesitate to enquire.", "pt": "Nao hesite em perguntar."}, {"en": "The event will commence at noon.", "pt": "O evento comecara ao meio-dia."}]$j$::jsonb,
$j$[{"q": "Formal de 'buy':", "ctx": "", "opts": ["purchase", "grab", "get", "pick up"], "ans": 0, "exp": "purchase = formal."}, {"q": "Formal de 'ask (info)':", "ctx": "", "opts": ["enquire", "ask", "wonder", "check"], "ans": 0, "exp": "enquire."}, {"q": "Formal de 'help':", "ctx": "", "opts": ["assist", "help out", "give a hand", "back up"], "ans": 0, "exp": "assist."}, {"q": "Formal de 'need':", "ctx": "", "opts": ["require", "need", "want", "gotta have"], "ans": 0, "exp": "require."}, {"q": "Formal de 'start':", "ctx": "", "opts": ["commence", "kick off", "get going", "start up"], "ans": 0, "exp": "commence."}, {"q": "Registro formal e ideal para:", "ctx": "", "opts": ["documentos/negocios", "bate-papo", "memes", "musica pop"], "ans": 0, "exp": "Contexto formal."}]$j$::jsonb),

('C2', 4039, $$Intensificadores fortes$$, $$utterly / bitterly / highly$$, $$💥$$,
$$Advertbios de grau colocam fortemente: utterly (completamente - utterly ridiculous), bitterly (amargamente - bitterly disappointed), highly (altamente - highly likely), deeply (profundamente), fully (plenamente). Cada um combina com certos adjetivos.$$,
$$Colocacao fixa: 'bitterly cold', 'highly unlikely', 'deeply moved'.$$,
$j$[{"en": "It's highly unlikely.", "pt": "E altamente improvavel."}, {"en": "She was bitterly disappointed.", "pt": "Ela ficou amargamente decepcionada."}, {"en": "That's utterly absurd.", "pt": "Isso e completamente absurdo."}]$j$::jsonb,
$j$[{"q": "Complete: ___ likely", "ctx": "", "opts": ["highly", "bitterly", "utterly", "deeply"], "ans": 0, "exp": "highly likely."}, {"q": "Complete: ___ disappointed", "ctx": "", "opts": ["bitterly", "highly", "fully", "widely"], "ans": 0, "exp": "bitterly disappointed."}, {"q": "Complete: ___ ridiculous", "ctx": "", "opts": ["utterly", "highly", "bitterly", "closely"], "ans": 0, "exp": "utterly ridiculous."}, {"q": "Complete: ___ cold", "ctx": "", "opts": ["bitterly", "highly", "deeply", "fully"], "ans": 0, "exp": "bitterly cold."}, {"q": "Complete: ___ moved (emocionado)", "ctx": "", "opts": ["deeply", "highly", "bitterly", "widely"], "ans": 0, "exp": "deeply moved."}, {"q": "Intensificadores combinam:", "ctx": "", "opts": ["por colocacao fixa", "com qualquer palavra", "so com verbos", "so no passado"], "ans": 0, "exp": "Colocacoes fixas."}]$j$::jsonb),

('C2', 4040, $$Phrasal verbs de negocios$$, $$roll out / scale up / wind down$$, $$📈$$,
$$Ingles corporativo: roll out (lancar), scale up/down (aumentar/reduzir escala), wind down (desacelerar/encerrar), branch out (diversificar), carry out (executar), lay off (demitir), pull off (conseguir apesar da dificuldade).$$,
$$'Roll out a product' = lancar gradualmente.$$,
$j$[{"en": "We'll roll out the new app in June.", "pt": "Vamos lancar o novo app em junho."}, {"en": "The company scaled up quickly.", "pt": "A empresa cresceu rapido."}, {"en": "They laid off 200 workers.", "pt": "Demitiram 200 funcionarios."}]$j$::jsonb,
$j$[{"q": "'Roll out' =", "ctx": "", "opts": ["lancar (gradualmente)", "enrolar", "cancelar", "esconder"], "ans": 0, "exp": "Lancamento."}, {"q": "'Scale up' =", "ctx": "", "opts": ["aumentar a escala", "reduzir", "medir", "escalar montanha"], "ans": 0, "exp": "Crescer."}, {"q": "'Lay off' =", "ctx": "", "opts": ["demitir", "contratar", "descansar", "atrasar"], "ans": 0, "exp": "Demitir."}, {"q": "'Wind down' =", "ctx": "", "opts": ["desacelerar/encerrar", "acelerar", "ventar", "subir"], "ans": 0, "exp": "Reduzir ritmo."}, {"q": "'Carry out' =", "ctx": "", "opts": ["executar/realizar", "carregar para fora", "cancelar", "adiar"], "ans": 0, "exp": "Executar."}, {"q": "'Pull off' (um plano) =", "ctx": "", "opts": ["conseguir apesar da dificuldade", "puxar", "desistir", "estragar"], "ans": 0, "exp": "Ter sucesso."}]$j$::jsonb),

('C2', 4041, $$Marcadores de discurso$$, $$mind you / come to think of it$$, $$💬$$,
$$Naturalidade vem de marcadores: mind you (olha, no entanto), come to think of it (pensando bem), as it happens (por acaso), that said (dito isso), to be fair (para ser justo), by the way (a proposito).$$,
$$'Mind you' introduz uma ressalva; 'come to think of it', uma lembranca.$$,
$j$[{"en": "He's rude. Mind you, he's honest.", "pt": "Ele e grosso. Mas, veja bem, e honesto."}, {"en": "Come to think of it, she did call.", "pt": "Pensando bem, ela ligou sim."}, {"en": "That said, we should try.", "pt": "Dito isso, devemos tentar."}]$j$::jsonb,
$j$[{"q": "'Mind you' introduz:", "ctx": "", "opts": ["uma ressalva", "uma ordem", "um pedido", "uma pergunta"], "ans": 0, "exp": "Ressalva."}, {"q": "'Come to think of it' =", "ctx": "", "opts": ["pensando bem", "esqueca", "definitivamente", "de novo"], "ans": 0, "exp": "Lembranca sobita."}, {"q": "'That said' =", "ctx": "", "opts": ["dito isso (contraste)", "ele disse", "cale-se", "concordo"], "ans": 0, "exp": "Transicao com ressalva."}, {"q": "'To be fair' =", "ctx": "", "opts": ["para ser justo", "com raiva", "de novo", "por fim"], "ans": 0, "exp": "Ponderar."}, {"q": "'By the way' =", "ctx": "", "opts": ["a proposito", "no caminho", "portanto", "porem"], "ans": 0, "exp": "Mudar de assunto."}, {"q": "Marcadores de discurso deixam a fala:", "ctx": "", "opts": ["mais natural e fluida", "mais formal so", "errada", "mais curta"], "ans": 0, "exp": "Naturalidade."}]$j$::jsonb),

('C2', 4042, $$Hedges e fillers na fala$$, $$sort of / I mean / kind of$$, $$🗨️$$,
$$Nativos suavizam e ganham tempo com: sort of / kind of (meio que), I mean (quer dizer), you know (sabe), like (tipo), or something (ou algo assim), more or less (mais ou menos). Em excesso soa inseguro; na medida, soa natural.$$,
$$'Kind of' suaviza: 'It's kind of expensive' = e meio caro.$$,
$j$[{"en": "It's kind of complicated.", "pt": "E meio complicado."}, {"en": "I mean, it could work.", "pt": "Quer dizer, poderia funcionar."}, {"en": "We need milk or something.", "pt": "Precisamos de leite ou algo assim."}]$j$::jsonb,
$j$[{"q": "'Kind of/sort of' =", "ctx": "", "opts": ["meio que (suaviza)", "exatamente", "nunca", "muito formal"], "ans": 0, "exp": "Suavizador."}, {"q": "'I mean' serve para:", "ctx": "", "opts": ["reformular/explicar", "ordenar", "negar", "perguntar"], "ans": 0, "exp": "Reformular."}, {"q": "'Or something' =", "ctx": "", "opts": ["ou algo do tipo", "com certeza", "nada", "de novo"], "ans": 0, "exp": "Imprecisao proposital."}, {"q": "Usar fillers em excesso soa:", "ctx": "", "opts": ["inseguro", "genial", "formal", "escrito"], "ans": 0, "exp": "Cuidado com o excesso."}, {"q": "'More or less' =", "ctx": "", "opts": ["mais ou menos", "muito", "pouco", "exato"], "ans": 0, "exp": "Aproximacao."}, {"q": "Na medida certa, fillers deixam a fala:", "ctx": "", "opts": ["mais natural", "mais robotica", "errada", "formal demais"], "ans": 0, "exp": "Naturalidade."}]$j$::jsonb),

('C2', 4043, $$Elipse na fala natural$$, $$You coming? Been there.$$, $$✂️$$,
$$Nativos omitem palavras obvias (elipse). 'Are you coming?' -> 'You coming?'. 'I have been there' -> 'Been there'. 'Do you want some?' -> 'Want some?'. Comum na fala informal, torna tudo mais agil.$$,
$$Cai o auxiliar/sujeito quando o sentido continua claro.$$,
$j$[{"en": "You coming tonight?", "pt": "Voce vem hoje a noite?"}, {"en": "Sounds good to me.", "pt": "Parece bom pra mim."}, {"en": "Told you so!", "pt": "Eu te avisei!"}]$j$::jsonb,
$j$[{"q": "'Are you ready?' vira (informal):", "ctx": "", "opts": ["You ready?", "You is ready?", "Ready you?", "Are ready?"], "ans": 0, "exp": "Cai o auxiliar."}, {"q": "'I have finished' vira:", "ctx": "", "opts": ["Finished!", "Have I finished", "Finish me", "I finish"], "ans": 0, "exp": "Elipse do sujeito+aux."}, {"q": "Elipse e comum em:", "ctx": "", "opts": ["fala informal", "contratos", "provas", "leis"], "ans": 0, "exp": "Informalidade."}, {"q": "'Do you want tea?' vira:", "ctx": "", "opts": ["Want some tea?", "You want is tea?", "Tea you?", "Want you tea?"], "ans": 0, "exp": "Cai 'do you'."}, {"q": "'Told you so' omite:", "ctx": "", "opts": ["I", "so", "you", "told"], "ans": 0, "exp": "Omite o sujeito 'I'."}, {"q": "A elipse deixa a fala:", "ctx": "", "opts": ["mais agil/natural", "mais longa", "formal", "escrita"], "ans": 0, "exp": "Agilidade."}]$j$::jsonb),

('C2', 4044, $$Fronting para enfase$$, $$This I have to see$$, $$⬅️$$,
$$Mover elementos para o inicio da frase da enfase (fronting). 'This I have to see' (isso eu preciso ver). 'Down came the rain'. 'Such was her joy that...'. Comum na escrita literaria e na fala enfatica.$$,
$$O objeto ou complemento vai para a frente para destacar.$$,
$j$[{"en": "That I don't believe.", "pt": "Nisso eu nao acredito."}, {"en": "Down came the rain.", "pt": "E a chuva desabou."}, {"en": "Such was his fear that he ran.", "pt": "Tamanho era seu medo que ele correu."}]$j$::jsonb,
$j$[{"q": "Fronting serve para:", "ctx": "", "opts": ["dar enfase", "fazer pergunta", "negar", "pedir"], "ans": 0, "exp": "Enfase."}, {"q": "'I don't believe that' com fronting:", "ctx": "", "opts": ["That I don't believe.", "That I believe don't.", "Believe that I don't.", "Don't that I believe."], "ans": 0, "exp": "Objeto para frente."}, {"q": "'Such was...' e:", "ctx": "", "opts": ["fronting enfatico", "erro", "pergunta", "condicional"], "ans": 0, "exp": "Estrutura enfatica."}, {"q": "Fronting e mais comum em:", "ctx": "", "opts": ["escrita literaria/fala enfatica", "e-mails de trabalho", "listas", "formularios"], "ans": 0, "exp": "Estilo/enfase."}, {"q": "'Down came the rain' destaca:", "ctx": "", "opts": ["a direcao/imagem (down)", "o sujeito so", "o tempo", "o lugar exato"], "ans": 0, "exp": "Efeito dramatico."}, {"q": "Fronting muda:", "ctx": "", "opts": ["a enfase, nao o sentido basico", "o sentido totalmente", "o tempo verbal", "o numero"], "ans": 0, "exp": "So a enfase."}]$j$::jsonb),

('C2', 4045, $$Subjuntivo em ingles$$, $$I suggest that he be...$$, $$📜$$,
$$O subjuntivo (formal) usa o verbo na forma base apos suggest, recommend, insist, demand, propose + that: 'I suggest that he BE present' (nao 'is'). Tambem em expressoes fixas: 'God save the Queen', 'Be that as it may'.$$,
$$Apos 'suggest/insist that', use o verbo sem conjugar: 'that she go', 'that he be'.$$,
$j$[{"en": "I recommend that he see a doctor.", "pt": "Recomendo que ele veja um medico."}, {"en": "They insisted that she be present.", "pt": "Insistiram que ela estivesse presente."}, {"en": "Be that as it may, we proceed.", "pt": "Seja como for, seguimos."}]$j$::jsonb,
$j$[{"q": "Complete: I suggest that he ___ early.", "ctx": "", "opts": ["leave", "leaves", "left", "is leaving"], "ans": 0, "exp": "Subjuntivo: forma base."}, {"q": "Complete: They demand that she ___ here.", "ctx": "", "opts": ["be", "is", "was", "being"], "ans": 0, "exp": "that she be (subjuntivo)."}, {"q": "O subjuntivo usa o verbo:", "ctx": "", "opts": ["na forma base", "sempre no passado", "com -ing", "com to"], "ans": 0, "exp": "Forma base."}, {"q": "Complete: I insist that he ___ the truth.", "ctx": "", "opts": ["tell", "tells", "told", "telling"], "ans": 0, "exp": "that he tell."}, {"q": "'Be that as it may' e:", "ctx": "", "opts": ["expressao fixa (seja como for)", "erro", "pergunta", "futuro"], "ans": 0, "exp": "Subjuntivo fossilizado."}, {"q": "O subjuntivo aparece muito em:", "ctx": "", "opts": ["ingles formal/americano", "girias", "mensagens", "musica pop"], "ans": 0, "exp": "Registro formal."}]$j$::jsonb),

('C2', 4046, $$Inversao avancada$$, $$No sooner had... than$$, $$🔃$$,
$$Estruturas enfaticas com inversao: 'No sooner had I arrived than it rained', 'Hardly had she left when...', 'Only after X did Y happen', 'Not until... did...'. Muito formais e literarias.$$,
$$'No sooner... than'; 'Hardly/Scarcely... when'.$$,
$j$[{"en": "No sooner had we sat down than he called.", "pt": "Mal nos sentamos e ele ligou."}, {"en": "Only then did I understand.", "pt": "So entao eu entendi."}, {"en": "Not until midnight did she sleep.", "pt": "So a meia-noite ela dormiu."}]$j$::jsonb,
$j$[{"q": "Complete: No sooner had I left ___ it rained.", "ctx": "", "opts": ["than", "when", "then", "that"], "ans": 0, "exp": "No sooner... than."}, {"q": "Complete: Hardly had he arrived ___ she left.", "ctx": "", "opts": ["when", "than", "then", "that"], "ans": 0, "exp": "Hardly... when."}, {"q": "Complete: Only then ___ I realize.", "ctx": "", "opts": ["did", "I did", "do", "was"], "ans": 0, "exp": "Inversao: did + I."}, {"q": "Complete: Not until 6pm ___ he call.", "ctx": "", "opts": ["did", "he did", "does", "was"], "ans": 0, "exp": "did + sujeito."}, {"q": "Essas estruturas sao:", "ctx": "", "opts": ["formais/literarias", "girias", "erros", "infantis"], "ans": 0, "exp": "Registro alto."}, {"q": "'Scarcely had... when' descreve:", "ctx": "", "opts": ["dois eventos quase simultaneos", "condicao", "futuro", "opiniao"], "ans": 0, "exp": "Sequencia rapida."}]$j$::jsonb),

('C2', 4047, $$Enfase: the very / the only$$, $$the very thing / the only one$$, $$🎯$$,
$$Para enfatizar: 'the very' (exatamente esse - the very thing I needed), 'the only' (o unico), 'the sheer' (puro/absoluto - the sheer size), 'own' (proprio - my own room). Reforcam com elegancia.$$,
$$'The very' = precisamente aquele; 'sheer' = puro/total.$$,
$j$[{"en": "This is the very book I wanted.", "pt": "Este e exatamente o livro que eu queria."}, {"en": "The sheer scale amazed us.", "pt": "A escala absoluta nos impressionou."}, {"en": "I have my own reasons.", "pt": "Tenho minhas proprias razoes."}]$j$::jsonb,
$j$[{"q": "'The very thing' =", "ctx": "", "opts": ["exatamente a coisa", "uma coisa qualquer", "a coisa errada", "quase a coisa"], "ans": 0, "exp": "Precisamente aquela."}, {"q": "'The sheer size' enfatiza:", "ctx": "", "opts": ["o tamanho puro/absoluto", "o tamanho pequeno", "a cor", "o preco"], "ans": 0, "exp": "sheer = puro/total."}, {"q": "'My own car' enfatiza:", "ctx": "", "opts": ["posse/exclusividade", "aluguel", "carro velho", "carro dos outros"], "ans": 0, "exp": "own = proprio."}, {"q": "'The only one' =", "ctx": "", "opts": ["o unico", "um dos varios", "o primeiro", "o ultimo"], "ans": 0, "exp": "Exclusividade."}, {"q": "'The very' vem antes de:", "ctx": "", "opts": ["um substantivo", "um verbo", "um adverbio", "uma preposicao"], "ans": 0, "exp": "the very + substantivo."}, {"q": "Essas formas servem para:", "ctx": "", "opts": ["reforcar com elegancia", "negar", "perguntar", "resumir"], "ans": 0, "exp": "Enfase elegante."}]$j$::jsonb),

('C2', 4048, $$Nominalizacao (academico)$$, $$decide -> the decision to$$, $$🎓$$,
$$Textos academicos preferem substantivos a verbos (nominalizacao). Em vez de 'They decided quickly', escreve-se 'The quick decision...'. 'Prices increased' -> 'The increase in prices'. Deixa o texto mais denso e impessoal.$$,
$$Transforme o verbo/acao em substantivo para soar academico.$$,
$j$[{"en": "The failure of the plan surprised us.", "pt": "O fracasso do plano nos surpreendeu."}, {"en": "There was a sharp rise in costs.", "pt": "Houve um aumento acentuado nos custos."}, {"en": "Her analysis was thorough.", "pt": "A analise dela foi minuciosa."}]$j$::jsonb,
$j$[{"q": "'They decided' nominalizado:", "ctx": "", "opts": ["the decision", "deciding fast", "decide it", "they decide"], "ans": 0, "exp": "verbo -> substantivo."}, {"q": "'Prices rose' nominalizado:", "ctx": "", "opts": ["the rise in prices", "prices rising up", "rise prices", "priced rise"], "ans": 0, "exp": "the rise."}, {"q": "Nominalizacao deixa o texto:", "ctx": "", "opts": ["mais denso/impessoal", "mais coloquial", "mais curto sempre", "errado"], "ans": 0, "exp": "Estilo academico."}, {"q": "'He analyzed the data' -> substantivo:", "ctx": "", "opts": ["his analysis of the data", "he analyze", "analyzing he", "data analyze"], "ans": 0, "exp": "analysis."}, {"q": "'They failed' -> substantivo:", "ctx": "", "opts": ["their failure", "failing them", "fail it", "they fail"], "ans": 0, "exp": "failure."}, {"q": "Nominalizacao e tipica de:", "ctx": "", "opts": ["escrita academica/formal", "conversa de bar", "memes", "SMS"], "ans": 0, "exp": "Registro academico."}]$j$::jsonb),

('C2', 4049, $$Voz passiva para objetividade$$, $$It was found that...$$, $$🔬$$,
$$Na escrita cientifica/formal, a passiva remove o agente e soa objetiva: 'The experiment was conducted', 'It was found that...', 'Data were collected'. Foca no processo, nao em quem fez.$$,
$$Use passiva quando quem age nao importa ou para soar impessoal.$$,
$j$[{"en": "The samples were analyzed carefully.", "pt": "As amostras foram analisadas com cuidado."}, {"en": "It was concluded that the drug works.", "pt": "Concluiu-se que o remedio funciona."}, {"en": "Mistakes were made.", "pt": "Erros foram cometidos."}]$j$::jsonb,
$j$[{"q": "'We conducted the test' na forma objetiva:", "ctx": "", "opts": ["The test was conducted", "We did test it", "Test we conduct", "Conducting test"], "ans": 0, "exp": "Passiva impessoal."}, {"q": "'It was found that' foca em:", "ctx": "", "opts": ["o resultado, nao quem achou", "a pessoa", "o tempo", "o lugar"], "ans": 0, "exp": "Objetividade."}, {"q": "A passiva academica remove:", "ctx": "", "opts": ["o agente (quem faz)", "o verbo", "o objeto", "o tempo"], "ans": 0, "exp": "Foco no processo."}, {"q": "'Data were collected' soa:", "ctx": "", "opts": ["objetivo/cientifico", "informal", "grosseiro", "poetico"], "ans": 0, "exp": "Registro cientifico."}, {"q": "'Mistakes were made' evita:", "ctx": "", "opts": ["apontar o culpado", "o passado", "o plural", "o verbo"], "ans": 0, "exp": "Omite o agente."}, {"q": "Passiva e preferida quando:", "ctx": "", "opts": ["o agente e irrelevante/impessoal", "queremos culpar alguem", "e informal", "ha pressa"], "ans": 0, "exp": "Objetividade."}]$j$::jsonb),

('C2', 4050, $$Conectores formais raros$$, $$notwithstanding / hence / thereby$$, $$🔗$$,
$$Conectores de alto registro: notwithstanding (nao obstante), hence/thus (portanto), thereby (assim/com isso), whereby (pelo qual), henceforth (de agora em diante), albeit (embora). Comuns em textos juridicos/academicos.$$,
$$'Albeit' = although, porem mais formal e curto: 'a small, albeit important, change'.$$,
$j$[{"en": "The plan, albeit risky, worked.", "pt": "O plano, embora arriscado, funcionou."}, {"en": "He was late; hence the delay.", "pt": "Ele atrasou; dai o atraso."}, {"en": "Notwithstanding the cost, we agreed.", "pt": "Nao obstante o custo, concordamos."}]$j$::jsonb,
$j$[{"q": "'Albeit' significa:", "ctx": "", "opts": ["embora (formal)", "portanto", "alem disso", "por exemplo"], "ans": 0, "exp": "= although (formal)."}, {"q": "'Hence' =", "ctx": "", "opts": ["portanto/dai", "porem", "depois", "antes"], "ans": 0, "exp": "Consequencia."}, {"q": "'Notwithstanding' =", "ctx": "", "opts": ["nao obstante/apesar de", "por causa de", "assim que", "enquanto"], "ans": 0, "exp": "Concessao formal."}, {"q": "'Thereby' =", "ctx": "", "opts": ["assim/com isso", "la", "quase", "porem"], "ans": 0, "exp": "Meio/resultado."}, {"q": "Esses conectores aparecem em:", "ctx": "", "opts": ["textos juridicos/academicos", "conversa casual", "memes", "receitas"], "ans": 0, "exp": "Alto registro."}, {"q": "'Henceforth' =", "ctx": "", "opts": ["de agora em diante", "no passado", "porem", "as vezes"], "ans": 0, "exp": "A partir de agora."}]$j$::jsonb),

('C2', 4051, $$Comparacoes idiomaticas$$, $$as good as gold$$, $$⚖️$$,
$$Comparacoes fixas (similes): as good as gold (comportado), like a fish out of water (deslocado), as easy as pie (facilimo), like water off a duck's back (nao faz efeito), as stubborn as a mule (teimoso).$$,
$$Sao fixas: nao troque as palavras (nao 'as good as silver').$$,
$j$[{"en": "The kids were as good as gold.", "pt": "As criancas se comportaram muito bem."}, {"en": "I felt like a fish out of water.", "pt": "Me senti totalmente deslocado."}, {"en": "It was as easy as pie.", "pt": "Foi facilimo."}]$j$::jsonb,
$j$[{"q": "'As good as gold' (sobre crianca) =", "ctx": "", "opts": ["muito comportada", "rica", "dourada", "travessa"], "ans": 0, "exp": "Bem comportada."}, {"q": "'Like a fish out of water' =", "ctx": "", "opts": ["deslocado/desconfortavel", "molhado", "com fome", "nadando bem"], "ans": 0, "exp": "Fora do ambiente."}, {"q": "'As easy as pie' =", "ctx": "", "opts": ["muito facil", "doce", "dificil", "gostoso"], "ans": 0, "exp": "Facilimo."}, {"q": "'Like water off a duck's back' =", "ctx": "", "opts": ["nao afeta a pessoa", "molhado", "rapido", "sujo"], "ans": 0, "exp": "Nao faz efeito."}, {"q": "'As stubborn as a mule' =", "ctx": "", "opts": ["muito teimoso", "forte", "lento", "burro literalmente"], "ans": 0, "exp": "Teimoso."}, {"q": "Similes idiomaticos sao:", "ctx": "", "opts": ["expressoes fixas", "livres para trocar", "erros", "gramatica"], "ans": 0, "exp": "Fixos."}]$j$::jsonb),

('C2', 4052, $$Eufemismos$$, $$passed away / let go$$, $$🕊️$$,
$$Eufemismos suavizam temas delicados: passed away (faleceu), let go / made redundant (demitido), between jobs (desempregado), put to sleep (sacrificar animal), economical with the truth (mentir educadamente), senior (idoso).$$,
$$Servem para soar sensivel: 'passed away' e mais gentil que 'died'.$$,
$j$[{"en": "Her grandfather passed away last year.", "pt": "O avo dela faleceu ano passado."}, {"en": "He was let go last month.", "pt": "Ele foi demitido mes passado."}, {"en": "I'm between jobs right now.", "pt": "Estou sem emprego no momento."}]$j$::jsonb,
$j$[{"q": "'Passed away' =", "ctx": "", "opts": ["faleceu (suave)", "viajou", "passou", "dormiu"], "ans": 0, "exp": "Eufemismo de 'died'."}, {"q": "'Let go' (no trabalho) =", "ctx": "", "opts": ["demitido", "promovido", "de ferias", "contratado"], "ans": 0, "exp": "Demitido (suave)."}, {"q": "'Between jobs' =", "ctx": "", "opts": ["desempregado (suave)", "com dois empregos", "ocupado", "aposentado"], "ans": 0, "exp": "Eufemismo."}, {"q": "Eufemismos servem para:", "ctx": "", "opts": ["suavizar temas delicados", "ofender", "encurtar", "confundir"], "ans": 0, "exp": "Sensibilidade."}, {"q": "'Economical with the truth' =", "ctx": "", "opts": ["mentir/omitir educadamente", "ser honesto", "economizar", "falar demais"], "ans": 0, "exp": "Eufemismo para mentir."}, {"q": "'Senior citizen' e eufemismo para:", "ctx": "", "opts": ["idoso", "chefe", "veterano", "estudante"], "ans": 0, "exp": "Idoso."}]$j$::jsonb),

('C2', 4053, $$Ironia e sarcasmo$$, $$Oh, great. Just what I needed.$$, $$🙃$$,
$$Ironia diz o oposto do sentido literal, sinalizada pelo tom/contexto: 'Oh, wonderful' (apos algo ruim), 'Just what I needed' (sarcastico), 'Well, that went well' (deu errado), 'Nice one' (voce errou). Entender ironia e chave no C2.$$,
$$O contexto revela: elogio + situacao ruim = sarcasmo.$$,
$j$[{"en": "Oh great, the car won't start.", "pt": "Otimo, o carro nao liga."}, {"en": "Well, that went well.", "pt": "Foi um sucesso... (ironico)."}, {"en": "Nice one, you broke it.", "pt": "Parabens, voce quebrou."}]$j$::jsonb,
$j$[{"q": "'Oh, great' apos um problema e:", "ctx": "", "opts": ["sarcasmo", "elogio real", "pergunta", "pedido"], "ans": 0, "exp": "Ironia."}, {"q": "Ironia diz:", "ctx": "", "opts": ["o oposto do literal", "sempre a verdade", "uma ordem", "um numero"], "ans": 0, "exp": "Sentido invertido."}, {"q": "'Well, that went well' (apos falha) =", "ctx": "", "opts": ["deu tudo errado", "foi otimo", "vamos de novo", "acabou bem"], "ans": 0, "exp": "Sarcasmo."}, {"q": "O que sinaliza a ironia?", "ctx": "", "opts": ["tom e contexto", "so a gramatica", "o plural", "o tempo verbal"], "ans": 0, "exp": "Tom/contexto."}, {"q": "'Nice one' (apos um erro) =", "ctx": "", "opts": ["critica sarcastica", "elogio sincero", "agradecimento", "duvida"], "ans": 0, "exp": "Sarcastico."}, {"q": "Entender ironia exige:", "ctx": "", "opts": ["ler o contexto", "so o dicionario", "sotaque perfeito", "vocabulario formal"], "ans": 0, "exp": "Contexto."}]$j$::jsonb),

('C2', 4054, $$Understatement e hiperbole$$, $$not bad / a million times$$, $$📉$$,
$$Understatement diminui (tipico UK): 'not bad' (= otimo), 'a bit of a problem' (= problemao), 'rather good'. Hiperbole exagera: 'I've told you a million times', 'starving', 'dying to see it'. Ambos sao expressivos.$$,
$$Understatement suaviza; hiperbole exagera para efeito.$$,
$j$[{"en": "The food was not bad at all.", "pt": "A comida estava otima (understatement)."}, {"en": "I'm starving!", "pt": "Estou morrendo de fome!"}, {"en": "I've said it a thousand times.", "pt": "Ja disse mil vezes."}]$j$::jsonb,
$j$[{"q": "'Not bad' (understatement) =", "ctx": "", "opts": ["bem bom", "pessimo", "normal", "estranho"], "ans": 0, "exp": "Elogio suavizado."}, {"q": "'I'm starving' e:", "ctx": "", "opts": ["hiperbole (exagero)", "literal (morrendo)", "understatement", "ironia"], "ans": 0, "exp": "Exagero."}, {"q": "Understatement e tipico do ingles:", "ctx": "", "opts": ["britanico", "tecnico", "antigo", "juridico"], "ans": 0, "exp": "Britanico."}, {"q": "'A bit of a problem' pode ser:", "ctx": "", "opts": ["um problema serio", "nada", "uma duvida", "uma piada"], "ans": 0, "exp": "Understatement."}, {"q": "Hiperbole serve para:", "ctx": "", "opts": ["enfatizar exagerando", "ser literal", "suavizar", "resumir"], "ans": 0, "exp": "Efeito enfatico."}, {"q": "'Dying to see it' =", "ctx": "", "opts": ["muito ansioso (exagero)", "literal morrer", "com medo", "sem interesse"], "ans": 0, "exp": "Hiperbole."}]$j$::jsonb),

('C2', 4055, $$Metafora no dia a dia$$, $$time is money$$, $$🧩$$,
$$Metaforas comuns tratam ideias abstratas como concretas: 'time is money' (tempo e valioso), 'a flood of emails' (muitos), 'the heart of the city' (centro), 'grasp an idea' (entender), 'a warm welcome'. Estao por toda parte no ingles.$$,
$$Nao sao literais: 'grasp an idea' e entender, nao segurar.$$,
$j$[{"en": "I got a flood of messages.", "pt": "Recebi uma enxurrada de mensagens."}, {"en": "She couldn't grasp the concept.", "pt": "Ela nao conseguiu captar o conceito."}, {"en": "We live in the heart of the city.", "pt": "Moramos no coracao da cidade."}]$j$::jsonb,
$j$[{"q": "'A flood of emails' =", "ctx": "", "opts": ["muitos emails", "emails molhados", "poucos", "spam so"], "ans": 0, "exp": "Metafora de quantidade."}, {"q": "'Grasp an idea' =", "ctx": "", "opts": ["entender", "segurar", "escrever", "esquecer"], "ans": 0, "exp": "Compreender."}, {"q": "'The heart of the city' =", "ctx": "", "opts": ["o centro", "o hospital", "a periferia", "o parque"], "ans": 0, "exp": "Centro."}, {"q": "'Time is money' significa:", "ctx": "", "opts": ["tempo e valioso", "dinheiro voa", "trabalhe menos", "seja rico"], "ans": 0, "exp": "Valor do tempo."}, {"q": "Metaforas tratam o abstrato como:", "ctx": "", "opts": ["algo concreto", "numeros", "verbos", "erros"], "ans": 0, "exp": "Concreto."}, {"q": "'A warm welcome' e:", "ctx": "", "opts": ["metafora (acolhedor)", "sobre temperatura", "erro", "literal"], "ans": 0, "exp": "Figurado."}]$j$::jsonb),

('C2', 4056, $$Homofonos que confundem$$, $$complement x compliment$$, $$🔊$$,
$$Palavras com som igual e sentido diferente: complement (completar) x compliment (elogio); stationary (parado) x stationery (papelaria); principal (diretor/principal) x principle (principio); their/there/they're.$$,
$$ComplIment com I = elogio ('I like your...'). ComplEment com E = completa.$$,
$j$[{"en": "She paid me a nice compliment.", "pt": "Ela me fez um belo elogio."}, {"en": "The wine complements the meal.", "pt": "O vinho complementa a refeicao."}, {"en": "The car was stationary.", "pt": "O carro estava parado."}]$j$::jsonb,
$j$[{"q": "'Elogio' escreve-se:", "ctx": "", "opts": ["compliment", "complement", "complyment", "complimant"], "ans": 0, "exp": "compliment (I) = elogio."}, {"q": "'Completar/combinar' escreve-se:", "ctx": "", "opts": ["complement", "compliment", "complament", "complimant"], "ans": 0, "exp": "complement (E)."}, {"q": "'Parado' (imovel):", "ctx": "", "opts": ["stationary", "stationery", "staitionary", "stationnary"], "ans": 0, "exp": "stationary (a) = parado."}, {"q": "'Papelaria/material':", "ctx": "", "opts": ["stationery", "stationary", "stationnery", "staytionery"], "ans": 0, "exp": "stationery (e) = papel."}, {"q": "'Principio/regra':", "ctx": "", "opts": ["principle", "principal", "principel", "principle"], "ans": 0, "exp": "principle = regra."}, {"q": "Homofonos tem:", "ctx": "", "opts": ["mesmo som, sentidos diferentes", "mesmo sentido", "mesma grafia", "sons diferentes"], "ans": 0, "exp": "Som igual, sentido diferente."}]$j$::jsonb),

('C2', 4057, $$Abreviacoes latinas$$, $$e.g. / i.e. / etc.$$, $$✍️$$,
$$Do latim, comuns na escrita: e.g. (por exemplo - exempli gratia), i.e. (isto e/ou seja - id est), etc. (e assim por diante), vs. (versus), et al. (e outros), N.B. (nota bem/atencao).$$,
$$Cuidado: e.g. = por exemplo; i.e. = ou seja. Nao sao sinonimos!$$,
$j$[{"en": "Bring fruit, e.g. apples or pears.", "pt": "Traga fruta, por exemplo macas ou peras."}, {"en": "It's due Friday, i.e. in two days.", "pt": "Vence sexta, ou seja, em dois dias."}, {"en": "See Smith et al., 2020.", "pt": "Ver Smith e outros, 2020."}]$j$::jsonb,
$j$[{"q": "'e.g.' significa:", "ctx": "", "opts": ["por exemplo", "ou seja", "e outros", "versus"], "ans": 0, "exp": "exempli gratia."}, {"q": "'i.e.' significa:", "ctx": "", "opts": ["ou seja/isto e", "por exemplo", "etc", "nota"], "ans": 0, "exp": "id est."}, {"q": "'et al.' =", "ctx": "", "opts": ["e outros (autores)", "e tudo", "por exemplo", "veja"], "ans": 0, "exp": "et alii."}, {"q": "'etc.' =", "ctx": "", "opts": ["e assim por diante", "exatamente", "porem", "ou seja"], "ans": 0, "exp": "et cetera."}, {"q": "'e.g.' e 'i.e.' sao:", "ctx": "", "opts": ["diferentes", "sinonimos", "iguais", "verbos"], "ans": 0, "exp": "Sentidos distintos."}, {"q": "'N.B.' pede:", "ctx": "", "opts": ["atencao (note bem)", "por exemplo", "fim", "versus"], "ans": 0, "exp": "nota bene."}]$j$::jsonb),

('C2', 4058, $$Contracoes coloquiais$$, $$gonna / wanna / gotta$$, $$🗯️$$,
$$Na fala rapida, reducoes: gonna (going to), wanna (want to), gotta (got to/have to), gimme (give me), lemme (let me), dunno (don't know), kinda (kind of). So na FALA/informal - nunca em texto formal.$$,
$$Entenda ao ouvir, mas nao escreva 'gonna' em e-mail profissional.$$,
$j$[{"en": "I'm gonna call her.", "pt": "Vou ligar pra ela."}, {"en": "I gotta go now.", "pt": "Tenho que ir agora."}, {"en": "I dunno what to say.", "pt": "Nao sei o que dizer."}]$j$::jsonb,
$j$[{"q": "'Gonna' = ", "ctx": "", "opts": ["going to", "gone to", "got to", "want to"], "ans": 0, "exp": "going to."}, {"q": "'Wanna' =", "ctx": "", "opts": ["want to", "went to", "won't", "was to"], "ans": 0, "exp": "want to."}, {"q": "'Gotta' =", "ctx": "", "opts": ["got to / have to", "go to", "gonna", "get it"], "ans": 0, "exp": "(have) got to."}, {"q": "Essas formas sao usadas:", "ctx": "", "opts": ["so na fala/informal", "em contratos", "em provas", "em leis"], "ans": 0, "exp": "Informal."}, {"q": "'Dunno' =", "ctx": "", "opts": ["don't know", "do now", "done", "did know"], "ans": 0, "exp": "don't know."}, {"q": "Em e-mail formal, deve-se:", "ctx": "", "opts": ["evitar essas contracoes", "usar sempre", "usar as vezes", "usar so no titulo"], "ans": 0, "exp": "Evitar no formal."}]$j$::jsonb),

('C2', 4059, $$Proverbios$$, $$the early bird catches the worm$$, $$🦉$$,
$$Proverbios sao sabedoria popular fixa: the early bird catches the worm (quem madruga), don't count your chickens (nao conte vitoria antes), actions speak louder than words, better late than never, when in Rome (faca como os locais).$$,
$$Muitas vezes so se diz o comeco: 'Well, when in Rome...'.$$,
$j$[{"en": "The early bird catches the worm.", "pt": "Deus ajuda quem cedo madruga."}, {"en": "Actions speak louder than words.", "pt": "Atos valem mais que palavras."}, {"en": "Better late than never.", "pt": "Antes tarde do que nunca."}]$j$::jsonb,
$j$[{"q": "'The early bird catches the worm' =", "ctx": "", "opts": ["quem se antecipa se da bem", "passaros comem cedo", "acorde tarde", "trabalhe menos"], "ans": 0, "exp": "Vantagem de agir cedo."}, {"q": "'Actions speak louder than words' =", "ctx": "", "opts": ["atos valem mais que promessas", "grite mais", "fale menos", "escreva tudo"], "ans": 0, "exp": "Atos > palavras."}, {"q": "'Don't count your chickens...' avisa para:", "ctx": "", "opts": ["nao comemorar cedo demais", "contar animais", "ter pressa", "desistir"], "ans": 0, "exp": "Nao antecipar vitoria."}, {"q": "'When in Rome...' sugere:", "ctx": "", "opts": ["adaptar-se aos costumes locais", "viajar", "aprender latim", "ficar em casa"], "ans": 0, "exp": "Faca como os locais."}, {"q": "Proverbios sao:", "ctx": "", "opts": ["frases fixas de sabedoria", "girias novas", "erros", "gramatica"], "ans": 0, "exp": "Ditados populares."}, {"q": "'Better late than never' =", "ctx": "", "opts": ["antes tarde do que nunca", "chegue cedo", "nunca atrase", "desista"], "ans": 0, "exp": "Melhor tarde que nunca."}]$j$::jsonb),

('C2', 4060, $$Giria x padrao (registro)$$, $$mate / awesome / knackered$$, $$🎚️$$,
$$Saber alternar registro e dominio pleno. Giria: mate/buddy (amigo), awesome/brilliant (otimo), knackered/beat (exausto), grand/bucks (dinheiro), cheers (obrigado/UK). Reconheca, mas escolha conforme o contexto formal ou casual.$$,
$$Girias criam intimidade; em contexto profissional, volte ao padrao.$$,
$j$[{"en": "Thanks, mate!", "pt": "Valeu, cara!"}, {"en": "I'm absolutely knackered.", "pt": "Estou exausto."}, {"en": "That's brilliant news.", "pt": "Que noticia otima."}]$j$::jsonb,
$j$[{"q": "'Mate' (UK) =", "ctx": "", "opts": ["amigo/cara", "colega de trabalho so", "chefe", "inimigo"], "ans": 0, "exp": "Amigo (informal)."}, {"q": "'Knackered' =", "ctx": "", "opts": ["exausto", "faminto", "feliz", "bravo"], "ans": 0, "exp": "Muito cansado."}, {"q": "'Cheers' (UK informal) pode significar:", "ctx": "", "opts": ["obrigado", "adeus formal", "desculpa", "por favor"], "ans": 0, "exp": "Valeu/saude."}, {"q": "Girias servem para:", "ctx": "", "opts": ["intimidade/informalidade", "documentos", "provas", "leis"], "ans": 0, "exp": "Contexto casual."}, {"q": "Em contexto profissional, o ideal e:", "ctx": "", "opts": ["usar o registro padrao", "usar so girias", "misturar sempre", "nao falar"], "ans": 0, "exp": "Padrao no formal."}, {"q": "Dominar registro significa:", "ctx": "", "opts": ["saber alternar formal e informal", "so falar formal", "so girias", "traduzir tudo"], "ans": 0, "exp": "Flexibilidade de registro."}]$j$::jsonb);

commit;
