-- ============================================================================
-- Vonai - Lote C1 (30 licoes avancadas ineditas, ordem 4001-4030)
-- Cole no Supabase -> SQL Editor -> RUN. Seguro rodar mais de uma vez.
-- Resposta correta e sempre a 1a opcao (ans:0); o app embaralha as opcoes.
-- ============================================================================
begin;
delete from licoes where ordem between 4001 and 4030;

insert into licoes (nivel, ordem, titulo, sub, icon, explicacao, dica, exemplos, questoes) values

('C1', 4001, $$Phrasal verbs separaveis$$, $$turn it off / turn off the light$$, $$🔀$$,
$$Muitos phrasal verbs sao separaveis: o objeto pode vir no meio (turn the TV off) ou no fim (turn off the TV). Mas se o objeto for um PRONOME (it, them), ele OBRIGATORIAMENTE vem no meio: turn it off.$$,
$$Regra de ouro: pronome sempre no meio. 'Turn off it' esta errado.$$,
$j$[{"en": "Please turn the light off.", "pt": "Por favor apague a luz."}, {"en": "I picked it up yesterday.", "pt": "Peguei isso ontem."}, {"en": "She threw the old letters away.", "pt": "Ela jogou as cartas velhas fora."}]$j$::jsonb,
$j$[{"q": "Com pronome, o correto e:", "ctx": "", "opts": ["turn it off", "turn off it", "off turn it", "it turn off"], "ans": 0, "exp": "Pronome sempre no meio."}, {"q": "Complete: Can you ___ (o casaco)?", "ctx": "", "opts": ["take it off", "take off it", "off take it", "take off"], "ans": 0, "exp": "take it off (pronome no meio)."}, {"q": "Qual esta errado?", "ctx": "", "opts": ["Pick up it", "Pick it up", "Pick up the box", "Pick the box up"], "ans": 0, "exp": "'Pick up it' e invalido."}, {"q": "'Throw away' com 'them':", "ctx": "", "opts": ["throw them away", "throw away them", "away throw them", "them throw away"], "ans": 0, "exp": "Pronome no meio."}, {"q": "Separavel significa que:", "ctx": "", "opts": ["o objeto pode ir no meio", "nunca se separa", "nao tem objeto", "so usa gerundio"], "ans": 0, "exp": "Objeto pode ir no meio."}, {"q": "Com substantivo ambos servem, EXCETO:", "ctx": "", "opts": ["Turn off it", "Turn off the radio", "Turn the radio off", "Turn it off"], "ans": 0, "exp": "So o pronome quebra a regra."}]$j$::jsonb),

('C1', 4002, $$Make x Do (avancado)$$, $$make a decision / do research$$, $$🛠️$$,
$$MAKE = criar, produzir, resultado (make a decision, make progress, make a mistake). DO = executar tarefa/atividade (do research, do the housework, do business). Sao colocacoes fixas que voce memoriza.$$,
$$Dica: make = algo novo surge; do = uma acao/tarefa e realizada.$$,
$j$[{"en": "We need to make a decision today.", "pt": "Precisamos tomar uma decisao hoje."}, {"en": "She does research at the university.", "pt": "Ela faz pesquisa na universidade."}, {"en": "They made a lot of progress.", "pt": "Eles fizeram muito progresso."}]$j$::jsonb,
$j$[{"q": "Complete: ___ a decision", "ctx": "", "opts": ["make", "do", "take", "have"], "ans": 0, "exp": "make a decision."}, {"q": "Complete: ___ the housework", "ctx": "", "opts": ["do", "make", "take", "give"], "ans": 0, "exp": "do the housework."}, {"q": "Complete: ___ progress", "ctx": "", "opts": ["make", "do", "get", "put"], "ans": 0, "exp": "make progress."}, {"q": "Complete: ___ business with", "ctx": "", "opts": ["do", "make", "take", "have"], "ans": 0, "exp": "do business."}, {"q": "Complete: ___ a mistake", "ctx": "", "opts": ["make", "do", "have", "get"], "ans": 0, "exp": "make a mistake."}, {"q": "Complete: ___ someone a favour", "ctx": "", "opts": ["do", "make", "give", "take"], "ans": 0, "exp": "do a favour."}]$j$::jsonb),

('C1', 4003, $$Inversao para enfase$$, $$Never have I seen...$$, $$🔁$$,
$$Em ingles formal, ao comecar a frase com advertbio negativo (never, rarely, seldom, not only, hardly), invertemos sujeito e verbo auxiliar: Never HAVE I seen such beauty.$$,
$$Depois do negativo inicial, use ordem de pergunta (auxiliar + sujeito).$$,
$j$[{"en": "Never have I seen such a mess.", "pt": "Nunca vi tamanha bagunca."}, {"en": "Rarely does he arrive late.", "pt": "Raramente ele chega atrasado."}, {"en": "Not only did she sing, she also danced.", "pt": "Ela nao so cantou, como tambem dancou."}]$j$::jsonb,
$j$[{"q": "Complete: Never ___ such a thing.", "ctx": "", "opts": ["have I heard", "I have heard", "I heard have", "heard I have"], "ans": 0, "exp": "Inversao apos 'never'."}, {"q": "Complete: Rarely ___ mistakes.", "ctx": "", "opts": ["does she make", "she makes", "she does make", "make she does"], "ans": 0, "exp": "does + sujeito + verbo."}, {"q": "'Not only... but also' pede:", "ctx": "", "opts": ["inversao", "ordem normal", "gerundio", "passado simples"], "ans": 0, "exp": "Inversao apos 'not only'."}, {"q": "A inversao soa:", "ctx": "", "opts": ["formal/enfatica", "informal", "errada", "infantil"], "ans": 0, "exp": "Enfase formal."}, {"q": "Complete: Hardly ___ when it rained.", "ctx": "", "opts": ["had we arrived", "we had arrived", "we arrived had", "arrived we had"], "ans": 0, "exp": "Inversao apos 'hardly'."}, {"q": "Qual esta correto?", "ctx": "", "opts": ["Seldom do I complain.", "Seldom I complain.", "Seldom I do complain.", "Seldom complain I."], "ans": 0, "exp": "do + I + verbo."}]$j$::jsonb),

('C1', 4004, $$Cleft sentences$$, $$What I need is time$$, $$✂️$$,
$$Frases clivadas destacam uma informacao. Comuns: 'It was X that...' (It was John that called) e 'What... is/was' (What I need is time). Servem para dar enfase a uma parte da frase.$$,
$$Use 'What + oracao + is' para enfatizar o que importa.$$,
$j$[{"en": "What I need is more time.", "pt": "O que eu preciso e mais tempo."}, {"en": "It was Ana who solved it.", "pt": "Foi a Ana que resolveu."}, {"en": "What she wants is respect.", "pt": "O que ela quer e respeito."}]$j$::jsonb,
$j$[{"q": "Complete: ___ I want is peace.", "ctx": "", "opts": ["What", "That", "Which", "Who"], "ans": 0, "exp": "What... is (clivada)."}, {"q": "Complete: It was John ___ called.", "ctx": "", "opts": ["who", "which", "what", "whose"], "ans": 0, "exp": "It was + pessoa + who."}, {"q": "Clivadas servem para:", "ctx": "", "opts": ["dar enfase", "fazer perguntas", "negar", "pedir"], "ans": 0, "exp": "Enfase."}, {"q": "Complete: ___ we did was leave.", "ctx": "", "opts": ["All", "Every", "Much", "Some"], "ans": 0, "exp": "All we did was..."}, {"q": "Escolha a clivada:", "ctx": "", "opts": ["What matters is honesty.", "Honesty matters.", "Is honesty matter.", "Matter honesty is."], "ans": 0, "exp": "Estrutura What... is."}, {"q": "'It was in 2020 that...' enfatiza:", "ctx": "", "opts": ["o tempo (quando)", "a pessoa", "o objeto", "o lugar"], "ans": 0, "exp": "Enfase no tempo."}]$j$::jsonb),

('C1', 4005, $$Mixed conditionals$$, $$If I had studied, I would be...$$, $$🔀$$,
$$Condicionais mistas combinam tempos. Passado->presente: 'If I had studied (passado), I would be rich now (presente)'. Presente->passado: 'If I were rich (agora), I would have bought it (antes)'.$$,
$$Olhe o TEMPO de cada parte: a condicao e o resultado podem estar em momentos diferentes.$$,
$j$[{"en": "If I had saved money, I would be free now.", "pt": "Se eu tivesse economizado, estaria livre agora."}, {"en": "If she were taller, she would have joined.", "pt": "Se ela fosse mais alta, teria entrado."}, {"en": "If he had slept, he wouldn't be tired.", "pt": "Se ele tivesse dormido, nao estaria cansado."}]$j$::jsonb,
$j$[{"q": "Complete: If I had left earlier, I ___ here now.", "ctx": "", "opts": ["would be", "would have been", "will be", "am"], "ans": 0, "exp": "Passado->presente: would be."}, {"q": "Complete: If I were rich, I ___ that car.", "ctx": "", "opts": ["would have bought", "would buy", "will buy", "bought"], "ans": 0, "exp": "Presente->passado: would have."}, {"q": "Mixed conditional combina:", "ctx": "", "opts": ["tempos diferentes", "so o presente", "so o futuro", "so imperativo"], "ans": 0, "exp": "Tempos diferentes."}, {"q": "'If I had studied, I would be a doctor' fala de:", "ctx": "", "opts": ["passado afetando o presente", "futuro", "so passado", "so presente"], "ans": 0, "exp": "Passado -> presente."}, {"q": "Complete: If she spoke French, she ___ the job.", "ctx": "", "opts": ["would have got", "would get", "will get", "got"], "ans": 0, "exp": "Presente habitual -> passado."}, {"q": "A parte 'if' com 'had + participio' e:", "ctx": "", "opts": ["passado irreal", "futuro", "presente real", "ordem"], "ans": 0, "exp": "Passado irreal (3o cond.)."}]$j$::jsonb),

('C1', 4006, $$Wish / If only$$, $$I wish I knew...$$, $$💭$$,
$$Para lamentos: WISH + passado (arrependimento do presente): 'I wish I knew' (queria saber). WISH + past perfect (arrependimento do passado): 'I wish I had studied'. WISH + would (reclamacao/irritacao): 'I wish he would stop'.$$,
$$'If only' = wish, mas mais dramatico.$$,
$j$[{"en": "I wish I knew the answer.", "pt": "Queria saber a resposta."}, {"en": "I wish I had gone to the party.", "pt": "Queria ter ido a festa."}, {"en": "I wish it would stop raining.", "pt": "Queria que parasse de chover."}]$j$::jsonb,
$j$[{"q": "Arrependimento do presente: I wish I ___.", "ctx": "", "opts": ["knew", "know", "have known", "will know"], "ans": 0, "exp": "wish + passado."}, {"q": "Arrependimento do passado: I wish I ___ harder.", "ctx": "", "opts": ["had studied", "studied", "study", "would study"], "ans": 0, "exp": "wish + past perfect."}, {"q": "Reclamacao: I wish he ___ calling.", "ctx": "", "opts": ["would stop", "stops", "stopped", "had stopped"], "ans": 0, "exp": "wish + would (irritacao)."}, {"q": "'If only' e:", "ctx": "", "opts": ["como wish, mais forte", "uma pergunta", "um comando", "um futuro"], "ans": 0, "exp": "Lamento enfatico."}, {"q": "Complete: I wish I ___ taller.", "ctx": "", "opts": ["were", "am", "will be", "have been"], "ans": 0, "exp": "wish + were (presente irreal)."}, {"q": "'I wish I had known' fala de:", "ctx": "", "opts": ["algo no passado", "algo no futuro", "um habito", "uma ordem"], "ans": 0, "exp": "Passado."}]$j$::jsonb),

('C1', 4007, $$Reported speech avancado$$, $$He said he had left$$, $$🗣️$$,
$$Ao relatar fala, os tempos recuam (backshift): present->past, past->past perfect, will->would, can->could. Tambem mudam pronomes e marcadores de tempo (now->then, today->that day).$$,
$$'I am tired' -> He said he was tired. 'I will go' -> She said she would go.$$,
$j$[{"en": "He said he was busy.", "pt": "Ele disse que estava ocupado."}, {"en": "She said she had finished.", "pt": "Ela disse que tinha terminado."}, {"en": "They said they would call.", "pt": "Eles disseram que ligariam."}]$j$::jsonb,
$j$[{"q": "'I am here' -> He said he ___ there.", "ctx": "", "opts": ["was", "is", "has been", "will be"], "ans": 0, "exp": "present->past."}, {"q": "'I finished' -> She said she ___.", "ctx": "", "opts": ["had finished", "finished", "has finished", "finishes"], "ans": 0, "exp": "past->past perfect."}, {"q": "'I will help' -> He said he ___ help.", "ctx": "", "opts": ["would", "will", "would have", "will have"], "ans": 0, "exp": "will->would."}, {"q": "'now' vira ___ no discurso indireto.", "ctx": "", "opts": ["then", "now", "today", "here"], "ans": 0, "exp": "now->then."}, {"q": "'I can swim' -> She said she ___ swim.", "ctx": "", "opts": ["could", "can", "could have", "will"], "ans": 0, "exp": "can->could."}, {"q": "'today' vira:", "ctx": "", "opts": ["that day", "today", "this day", "now"], "ans": 0, "exp": "today->that day."}]$j$::jsonb),

('C1', 4008, $$Passiva com reporting verbs$$, $$It is said that...$$, $$📢$$,
$$Estrutura formal para relatar rumores/opinioes: 'It is said that he is rich' ou 'He is said to be rich'. Comum em noticias. Verbos: say, believe, think, know, report, expect.$$,
$$Duas formas: It is said that + oracao / Sujeito + is said + to + infinitivo.$$,
$j$[{"en": "It is believed that he left.", "pt": "Acredita-se que ele partiu."}, {"en": "She is said to be very rich.", "pt": "Dizem que ela e muito rica."}, {"en": "The company is expected to grow.", "pt": "Espera-se que a empresa cresca."}]$j$::jsonb,
$j$[{"q": "Complete: It is ___ that he is guilty.", "ctx": "", "opts": ["believed", "believe", "believing", "believes"], "ans": 0, "exp": "It is believed that..."}, {"q": "Complete: He is said ___ rich.", "ctx": "", "opts": ["to be", "being", "is", "be"], "ans": 0, "exp": "is said to be."}, {"q": "Essa estrutura e tipica de:", "ctx": "", "opts": ["noticias/formal", "conversa casual", "mensagens", "girias"], "ans": 0, "exp": "Registro formal."}, {"q": "Complete: The plan is ___ to work.", "ctx": "", "opts": ["expected", "expect", "expecting", "expects"], "ans": 0, "exp": "is expected to."}, {"q": "'It is known that' significa:", "ctx": "", "opts": ["sabe-se que", "eu sei que", "conheco", "conhecido"], "ans": 0, "exp": "Sabe-se que (impessoal)."}, {"q": "Complete: They are ___ to have won.", "ctx": "", "opts": ["thought", "think", "thinking", "thinks"], "ans": 0, "exp": "are thought to have."}]$j$::jsonb),

('C1', 4009, $$Reduced relative clauses$$, $$the man standing there$$, $$✂️$$,
$$Podemos encurtar oracoes relativas. Ativa: 'the man WHO IS standing' -> 'the man standing'. Passiva: 'the book WHICH WAS written' -> 'the book written'. Corta o pronome relativo + verbo be.$$,
$$Ativa vira -ing; passiva vira participio (-ed/3a coluna).$$,
$j$[{"en": "The woman talking is my boss.", "pt": "A mulher que esta falando e minha chefe."}, {"en": "The letter sent yesterday arrived.", "pt": "A carta enviada ontem chegou."}, {"en": "People living here are friendly.", "pt": "As pessoas que moram aqui sao simpaticas."}]$j$::jsonb,
$j$[{"q": "'The man who is waiting' encurta para:", "ctx": "", "opts": ["The man waiting", "The man wait", "The man to wait", "The man waited"], "ans": 0, "exp": "Ativa -> -ing."}, {"q": "'The car which was stolen' encurta para:", "ctx": "", "opts": ["The car stolen", "The car stealing", "The car steal", "The car to steal"], "ans": 0, "exp": "Passiva -> participio."}, {"q": "A forma reduzida ativa usa:", "ctx": "", "opts": ["-ing", "-ed sempre", "to + verbo", "will"], "ans": 0, "exp": "Gerundio."}, {"q": "'The book written by her' vem de:", "ctx": "", "opts": ["which was written", "which writes", "who write", "that writing"], "ans": 0, "exp": "Passiva reduzida."}, {"q": "Reduzir clausulas deixa o texto:", "ctx": "", "opts": ["mais conciso", "mais longo", "informal", "errado"], "ans": 0, "exp": "Mais conciso."}, {"q": "Complete: The people ___ (que esperam) are tired.", "ctx": "", "opts": ["waiting", "waited", "to wait", "waits"], "ans": 0, "exp": "Ativa -> waiting."}]$j$::jsonb),

('C1', 4010, $$Participle clauses$$, $$Having finished, she left$$, $$📝$$,
$$Clausulas participiais economizam palavras. -ing (ativa/simultanea): 'Feeling tired, I slept'. Having + participio (acao anterior): 'Having eaten, we left'. Participio passado (passiva): 'Shocked, she froze'.$$,
$$Sao formais e comuns na escrita. O sujeito das duas partes deve ser o mesmo.$$,
$j$[{"en": "Feeling sick, he stayed home.", "pt": "Sentindo-se mal, ele ficou em casa."}, {"en": "Having read the book, she wrote a review.", "pt": "Tendo lido o livro, ela escreveu uma resenha."}, {"en": "Built in 1900, the house is old.", "pt": "Construida em 1900, a casa e antiga."}]$j$::jsonb,
$j$[{"q": "Acao anterior usa:", "ctx": "", "opts": ["Having + participio", "-ing simples", "to + verbo", "will"], "ans": 0, "exp": "Having eaten..."}, {"q": "Complete: ___ tired, she rested.", "ctx": "", "opts": ["Feeling", "Felt", "To feel", "Feels"], "ans": 0, "exp": "-ing simultaneo."}, {"q": "'Built in 1990' e:", "ctx": "", "opts": ["participio passivo", "gerundio", "infinitivo", "presente"], "ans": 0, "exp": "Passiva reduzida."}, {"q": "As duas partes devem ter:", "ctx": "", "opts": ["o mesmo sujeito", "sujeitos diferentes", "sem sujeito", "dois verbos be"], "ans": 0, "exp": "Mesmo sujeito."}, {"q": "Complete: ___ finished, they went home.", "ctx": "", "opts": ["Having", "Have", "Has", "To have"], "ans": 0, "exp": "Having finished."}, {"q": "Clausulas participiais sao:", "ctx": "", "opts": ["formais/escritas", "so faladas", "erradas", "infantis"], "ans": 0, "exp": "Registro formal."}]$j$::jsonb),

('C1', 4011, $$Gerundio x infinitivo (sentido)$$, $$stop smoking / stop to smoke$$, $$🔄$$,
$$Alguns verbos mudam de sentido: 'stop smoking' (parar de fumar) vs 'stop to smoke' (parar para fumar). 'remember doing' (lembrar de algo feito) vs 'remember to do' (lembrar de fazer). 'try doing' (experimentar) vs 'try to do' (esforcar-se).$$,
$$Infinitivo = proposito/futuro; gerundio = acao em si/passado.$$,
$j$[{"en": "I stopped to rest.", "pt": "Parei para descansar."}, {"en": "Remember to lock the door.", "pt": "Lembre de trancar a porta."}, {"en": "I remember meeting her.", "pt": "Lembro de te-la conhecido."}]$j$::jsonb,
$j$[{"q": "'Parar de fumar':", "ctx": "", "opts": ["stop smoking", "stop to smoke", "stop smoke", "stop for smoke"], "ans": 0, "exp": "stop + -ing = cessar."}, {"q": "'Parou para descansar':", "ctx": "", "opts": ["stopped to rest", "stopped resting", "stop rest", "stopped rest"], "ans": 0, "exp": "stop to = proposito."}, {"q": "'Lembre de ligar' (tarefa futura):", "ctx": "", "opts": ["remember to call", "remember calling", "remember call", "remember for call"], "ans": 0, "exp": "remember to = futuro."}, {"q": "'Lembro de ter visto':", "ctx": "", "opts": ["remember seeing", "remember to see", "remember see", "remember for see"], "ans": 0, "exp": "remember + -ing = passado."}, {"q": "'Experimente ligar de novo' (sugestao):", "ctx": "", "opts": ["try calling again", "try to call", "try call", "try for call"], "ans": 0, "exp": "try + -ing = experimentar."}, {"q": "Infinitivo (to) costuma indicar:", "ctx": "", "opts": ["proposito/futuro", "acao passada", "habito", "duracao"], "ans": 0, "exp": "Proposito/futuro."}]$j$::jsonb),

('C1', 4012, $$Future perfect / continuous$$, $$I will have finished by 5$$, $$⏳$$,
$$Future perfect: acao concluida ANTES de um ponto futuro: 'By 6 pm I will have finished'. Future continuous: acao em andamento em um momento futuro: 'This time tomorrow I will be flying'.$$,
$$'By + tempo' pede future perfect. 'At this time' pede future continuous.$$,
$j$[{"en": "By 2030 I will have graduated.", "pt": "Ate 2030 eu terei me formado."}, {"en": "This time tomorrow we will be traveling.", "pt": "Amanha a esta hora estaremos viajando."}, {"en": "She will have left by then.", "pt": "Ela ja tera saido ate la."}]$j$::jsonb,
$j$[{"q": "Complete: By 8, I ___ dinner.", "ctx": "", "opts": ["will have made", "will make", "will be making", "make"], "ans": 0, "exp": "By + future perfect."}, {"q": "Complete: This time tomorrow I ___.", "ctx": "", "opts": ["will be sleeping", "will have slept", "sleep", "will sleep"], "ans": 0, "exp": "Acao em andamento futura."}, {"q": "'By then' combina com:", "ctx": "", "opts": ["future perfect", "present simple", "past simple", "imperativo"], "ans": 0, "exp": "By then + will have."}, {"q": "Future perfect indica acao:", "ctx": "", "opts": ["concluida antes de um ponto futuro", "em andamento", "habitual", "passada"], "ans": 0, "exp": "Concluida antes."}, {"q": "Complete: In an hour she ___ working.", "ctx": "", "opts": ["will still be", "will have", "is", "was"], "ans": 0, "exp": "Continuous futuro."}, {"q": "'will have + participio' e:", "ctx": "", "opts": ["future perfect", "future continuous", "present perfect", "past perfect"], "ans": 0, "exp": "Future perfect."}]$j$::jsonb),

('C1', 4013, $$Modais de deducao no passado$$, $$must have / can't have$$, $$🔍$$,
$$Para deduzir sobre o passado: 'must have + participio' (certeza positiva: deve ter), 'can't have' (certeza negativa: nao pode ter), 'might/could have' (possibilidade: talvez tenha).$$,
$$must have = tenho certeza que sim; can't have = tenho certeza que nao.$$,
$j$[{"en": "He must have forgotten.", "pt": "Ele deve ter esquecido."}, {"en": "She can't have seen us.", "pt": "Ela nao pode ter nos visto."}, {"en": "They might have missed the train.", "pt": "Eles talvez tenham perdido o trem."}]$j$::jsonb,
$j$[{"q": "Certeza positiva sobre o passado:", "ctx": "", "opts": ["must have left", "can't have left", "might leave", "should leave"], "ans": 0, "exp": "must have = certeza."}, {"q": "Certeza negativa:", "ctx": "", "opts": ["can't have known", "must have known", "might know", "could know"], "ans": 0, "exp": "can't have = impossivel."}, {"q": "Possibilidade:", "ctx": "", "opts": ["might have gone", "must have gone", "can't have gone", "will go"], "ans": 0, "exp": "might have = talvez."}, {"q": "Complete: The ground is wet. It ___ rained.", "ctx": "", "opts": ["must have", "can't have", "shouldn't have", "will have"], "ans": 0, "exp": "Deducao logica: must have."}, {"q": "'She can't have said that' expressa:", "ctx": "", "opts": ["forte descrenca", "certeza positiva", "obrigacao", "permissao"], "ans": 0, "exp": "Impossibilidade percebida."}, {"q": "Todos usam a estrutura:", "ctx": "", "opts": ["modal + have + participio", "modal + -ing", "modal + to", "modal + will"], "ans": 0, "exp": "modal + have + participio."}]$j$::jsonb),

('C1', 4014, $$Despite x Although$$, $$despite the rain / although it rained$$, $$🌧️$$,
$$Mesma ideia (contraste), estruturas diferentes. ALTHOUGH/THOUGH + oracao (sujeito+verbo): 'Although it rained, we went'. DESPITE/IN SPITE OF + substantivo ou -ing: 'Despite the rain' / 'Despite raining'.$$,
$$Nunca 'despite of'. E 'in spite OF' ou 'despite' (sem of).$$,
$j$[{"en": "Although he was tired, he worked.", "pt": "Embora estivesse cansado, ele trabalhou."}, {"en": "Despite the cost, they bought it.", "pt": "Apesar do custo, compraram."}, {"en": "In spite of being ill, she came.", "pt": "Apesar de estar doente, ela veio."}]$j$::jsonb,
$j$[{"q": "Complete: ___ the traffic, we arrived.", "ctx": "", "opts": ["Despite", "Although", "Even", "But"], "ans": 0, "exp": "Despite + substantivo."}, {"q": "Complete: ___ it was late, we stayed.", "ctx": "", "opts": ["Although", "Despite", "In spite", "Despite of"], "ans": 0, "exp": "Although + oracao."}, {"q": "Qual esta errado?", "ctx": "", "opts": ["Despite of the rain", "Despite the rain", "In spite of the rain", "Although it rained"], "ans": 0, "exp": "'Despite of' nao existe."}, {"q": "Complete: Despite ___ hard, he failed.", "ctx": "", "opts": ["working", "he worked", "work", "to work"], "ans": 0, "exp": "Despite + -ing."}, {"q": "'Although' e seguido de:", "ctx": "", "opts": ["sujeito + verbo", "substantivo so", "-ing so", "of"], "ans": 0, "exp": "Oracao completa."}, {"q": "'In spite ___ the noise' completa com:", "ctx": "", "opts": ["of", "on", "to", "for"], "ans": 0, "exp": "in spite of."}]$j$::jsonb),

('C1', 4015, $$Conectivos formais$$, $$however / therefore / nevertheless$$, $$🔗$$,
$$Conectores ligam ideias em texto formal. Contraste: however, nevertheless, on the other hand. Resultado: therefore, thus, consequently. Adicao: moreover, furthermore. Geralmente vem com virgula.$$,
$$However = porem; therefore = portanto; moreover = alem disso.$$,
$j$[{"en": "It was expensive; however, we bought it.", "pt": "Era caro; porem, compramos."}, {"en": "He was late; therefore, he missed it.", "pt": "Ele atrasou; portanto, perdeu."}, {"en": "Moreover, the plan saves money.", "pt": "Alem disso, o plano economiza."}]$j$::jsonb,
$j$[{"q": "'Porem' formal:", "ctx": "", "opts": ["however", "moreover", "therefore", "because"], "ans": 0, "exp": "however = contraste."}, {"q": "'Portanto':", "ctx": "", "opts": ["therefore", "however", "although", "moreover"], "ans": 0, "exp": "therefore = resultado."}, {"q": "'Alem disso':", "ctx": "", "opts": ["furthermore", "however", "therefore", "instead"], "ans": 0, "exp": "furthermore = adicao."}, {"q": "'Nevertheless' significa:", "ctx": "", "opts": ["mesmo assim", "por isso", "por exemplo", "primeiro"], "ans": 0, "exp": "Contraste (ainda assim)."}, {"q": "'Consequently' indica:", "ctx": "", "opts": ["resultado", "contraste", "adicao", "exemplo"], "ans": 0, "exp": "Consequencia."}, {"q": "Esses conectores sao mais comuns em:", "ctx": "", "opts": ["texto formal", "girias", "mensagens", "musicas"], "ans": 0, "exp": "Registro formal."}]$j$::jsonb),

('C1', 4016, $$Phrasal verbs com UP$$, $$give up / bring up / make up$$, $$⬆️$$,
$$'Up' costuma dar ideia de completar ou intensificar. give up (desistir), bring up (criar/mencionar), make up (inventar/reconciliar), come up with (bolar), put up with (tolerar).$$,
$$Muitos sao idiomaticos: 'make up' pode ser inventar OU reconciliar, depende do contexto.$$,
$j$[{"en": "Don't give up now.", "pt": "Nao desista agora."}, {"en": "She brought up an interesting point.", "pt": "Ela levantou um ponto interessante."}, {"en": "I can't put up with this noise.", "pt": "Nao aguento esse barulho."}]$j$::jsonb,
$j$[{"q": "'Desistir' =", "ctx": "", "opts": ["give up", "give in", "give out", "give away"], "ans": 0, "exp": "give up = desistir."}, {"q": "'Tolerar/aguentar' =", "ctx": "", "opts": ["put up with", "put up", "put down", "put off"], "ans": 0, "exp": "put up with."}, {"q": "'Bolar uma ideia' =", "ctx": "", "opts": ["come up with", "come up", "come across", "come over"], "ans": 0, "exp": "come up with."}, {"q": "'Bring up' pode significar:", "ctx": "", "opts": ["criar (filhos) ou mencionar", "derrubar", "esconder", "vender"], "ans": 0, "exp": "Criar/mencionar."}, {"q": "'Make up a story' =", "ctx": "", "opts": ["inventar", "escrever bem", "traduzir", "corrigir"], "ans": 0, "exp": "make up = inventar."}, {"q": "'Up' nesses verbos costuma dar ideia de:", "ctx": "", "opts": ["completar/intensificar", "descer", "parar", "repetir"], "ans": 0, "exp": "Completude/intensidade."}]$j$::jsonb),

('C1', 4017, $$Colocacoes com TAKE$$, $$take part / take advantage$$, $$🤝$$,
$$TAKE forma muitas colocacoes fixas: take part (participar), take advantage of (aproveitar-se), take place (acontecer), take care of (cuidar), take into account (levar em conta), take responsibility.$$,
$$Memorize como blocos: 'take place' = ocorrer, nao 'happen place'.$$,
$j$[{"en": "The meeting takes place at noon.", "pt": "A reuniao acontece ao meio-dia."}, {"en": "We took advantage of the offer.", "pt": "Aproveitamos a oferta."}, {"en": "Please take this into account.", "pt": "Por favor leve isso em conta."}]$j$::jsonb,
$j$[{"q": "'Acontecer' =", "ctx": "", "opts": ["take place", "take part", "take care", "take time"], "ans": 0, "exp": "take place."}, {"q": "'Participar' =", "ctx": "", "opts": ["take part in", "take place", "take part of", "make part"], "ans": 0, "exp": "take part in."}, {"q": "'Levar em conta' =", "ctx": "", "opts": ["take into account", "take account", "take in count", "make account"], "ans": 0, "exp": "take into account."}, {"q": "'Cuidar de' =", "ctx": "", "opts": ["take care of", "take care", "make care of", "give care"], "ans": 0, "exp": "take care of."}, {"q": "'Aproveitar-se de' =", "ctx": "", "opts": ["take advantage of", "take advantage", "make advantage", "get advantage"], "ans": 0, "exp": "take advantage of."}, {"q": "Colocacoes sao:", "ctx": "", "opts": ["combinacoes fixas de palavras", "girias", "erros", "abreviacoes"], "ans": 0, "exp": "Combinacoes naturais fixas."}]$j$::jsonb),

('C1', 4018, $$Adjetivo + preposicao$$, $$good at / afraid of$$, $$🔤$$,
$$Adjetivos pedem preposicoes fixas: good AT, afraid OF, interested IN, proud OF, keen ON, responsible FOR, similar TO, different FROM. Sao arbitrarias - memorize.$$,
$$Cuidado: 'good in' esta errado; e 'good AT'.$$,
$j$[{"en": "She is good at math.", "pt": "Ela e boa em matematica."}, {"en": "I'm interested in art.", "pt": "Tenho interesse em arte."}, {"en": "He's afraid of dogs.", "pt": "Ele tem medo de cachorros."}]$j$::jsonb,
$j$[{"q": "good ___ something", "ctx": "", "opts": ["at", "in", "on", "of"], "ans": 0, "exp": "good at."}, {"q": "afraid ___ spiders", "ctx": "", "opts": ["of", "to", "for", "with"], "ans": 0, "exp": "afraid of."}, {"q": "interested ___ music", "ctx": "", "opts": ["in", "on", "at", "for"], "ans": 0, "exp": "interested in."}, {"q": "proud ___ you", "ctx": "", "opts": ["of", "for", "with", "at"], "ans": 0, "exp": "proud of."}, {"q": "responsible ___ the team", "ctx": "", "opts": ["for", "of", "to", "on"], "ans": 0, "exp": "responsible for."}, {"q": "different ___ mine (US)", "ctx": "", "opts": ["from", "than", "of", "to"], "ans": 0, "exp": "different from."}]$j$::jsonb),

('C1', 4019, $$Verbo + preposicao$$, $$depend on / apologize for$$, $$🔤$$,
$$Verbos pedem preposicoes fixas: depend ON, apologize FOR, believe IN, succeed IN, insist ON, rely ON, deal WITH, consist OF, accuse OF. Memorize por uso.$$,
$$'Depend of' esta errado; e 'depend ON'.$$,
$j$[{"en": "It depends on you.", "pt": "Depende de voce."}, {"en": "She apologized for the delay.", "pt": "Ela se desculpou pelo atraso."}, {"en": "We rely on teamwork.", "pt": "Contamos com o trabalho em equipe."}]$j$::jsonb,
$j$[{"q": "depend ___ someone", "ctx": "", "opts": ["on", "of", "in", "to"], "ans": 0, "exp": "depend on."}, {"q": "apologize ___ a mistake", "ctx": "", "opts": ["for", "of", "about", "to"], "ans": 0, "exp": "apologize for."}, {"q": "believe ___ yourself", "ctx": "", "opts": ["in", "on", "of", "at"], "ans": 0, "exp": "believe in."}, {"q": "consist ___ three parts", "ctx": "", "opts": ["of", "in", "on", "with"], "ans": 0, "exp": "consist of."}, {"q": "deal ___ a problem", "ctx": "", "opts": ["with", "on", "of", "for"], "ans": 0, "exp": "deal with."}, {"q": "insist ___ paying", "ctx": "", "opts": ["on", "in", "at", "for"], "ans": 0, "exp": "insist on."}]$j$::jsonb),

('C1', 4020, $$Enfase com so / such$$, $$so tired / such a day$$, $$❗$$,
$$Para intensificar: SO + adjetivo/adverbio (so tired, so quickly). SUCH + (a/an) + adjetivo + substantivo (such a nice day, such good food). Uncountable/plural nao leva a/an: such nice weather.$$,
$$so = com adjetivo sozinho; such = quando ha substantivo.$$,
$j$[{"en": "It was so cold.", "pt": "Estava tao frio."}, {"en": "It was such a cold day.", "pt": "Foi um dia tao frio."}, {"en": "They have such nice ideas.", "pt": "Eles tem ideias tao boas."}]$j$::jsonb,
$j$[{"q": "Complete: She is ___ kind.", "ctx": "", "opts": ["so", "such", "such a", "very such"], "ans": 0, "exp": "so + adjetivo."}, {"q": "Complete: It was ___ good film.", "ctx": "", "opts": ["such a", "so", "so a", "such"], "ans": 0, "exp": "such a + adj + subst."}, {"q": "Complete: The food was ___ delicious.", "ctx": "", "opts": ["so", "such", "such a", "so a"], "ans": 0, "exp": "so + adjetivo."}, {"q": "Complete: ___ nice people!", "ctx": "", "opts": ["Such", "So", "Such a", "So a"], "ans": 0, "exp": "such (plural, sem a)."}, {"q": "Complete: We had ___ fun.", "ctx": "", "opts": ["such", "such a", "so a", "a so"], "ans": 0, "exp": "such + uncountable."}, {"q": "'So' e usado com:", "ctx": "", "opts": ["adjetivo/adverbio", "substantivo + a", "verbo", "artigo"], "ans": 0, "exp": "so + adj/adv."}]$j$::jsonb),

('C1', 4021, $$Substantivos incontaveis$$, $$advice / information / news$$, $$📦$$,
$$Muitos substantivos sao incontaveis em ingles (mas contaveis em portugues): advice, information, news, furniture, luggage, equipment, research, knowledge. Nao usam 'a/an' nem plural. Use 'a piece of' para contar.$$,
$$Errado: 'an advice', 'informations'. Certo: 'a piece of advice', 'information'.$$,
$j$[{"en": "Let me give you some advice.", "pt": "Deixe-me te dar um conselho."}, {"en": "I need more information.", "pt": "Preciso de mais informacoes."}, {"en": "The news is good.", "pt": "As noticias sao boas."}]$j$::jsonb,
$j$[{"q": "Qual esta correto?", "ctx": "", "opts": ["some advice", "an advice", "advices", "many advice"], "ans": 0, "exp": "advice e incontavel."}, {"q": "'Uma informacao' =", "ctx": "", "opts": ["a piece of information", "an information", "one information", "a information"], "ans": 0, "exp": "a piece of information."}, {"q": "'News' leva verbo:", "ctx": "", "opts": ["singular (is)", "plural (are)", "os dois", "nenhum"], "ans": 0, "exp": "The news IS..."}, {"q": "Qual e incontavel?", "ctx": "", "opts": ["furniture", "chair", "table", "book"], "ans": 0, "exp": "furniture e incontavel."}, {"q": "Qual esta errado?", "ctx": "", "opts": ["two luggages", "some luggage", "a lot of luggage", "my luggage"], "ans": 0, "exp": "luggage nao pluraliza."}, {"q": "'Research' no plural:", "ctx": "", "opts": ["nao pluraliza (research)", "researches", "researchs", "researchies"], "ans": 0, "exp": "Incontavel."}]$j$::jsonb),

('C1', 4022, $$Artigos avancados$$, $$the / a / zero article$$, $$🅰️$$,
$$Uso generico: sem artigo para plural/incontavel geral (I like music; Dogs are loyal). THE para algo especifico ou unico (the sun, the government). Sem artigo com refeicoes, esportes, idiomas (have lunch, play tennis, speak French).$$,
$$Generalizacao no plural = sem artigo. Especifico = the.$$,
$j$[{"en": "Music makes me happy.", "pt": "Musica me deixa feliz."}, {"en": "The music at the party was loud.", "pt": "A musica na festa estava alta."}, {"en": "She plays tennis on Sundays.", "pt": "Ela joga tenis aos domingos."}]$j$::jsonb,
$j$[{"q": "Geral: I love ___ (cachorros).", "ctx": "", "opts": ["dogs", "the dogs", "a dogs", "dog"], "ans": 0, "exp": "Generico = sem the."}, {"q": "Complete: ___ sun is bright.", "ctx": "", "opts": ["The", "A", "An", "(nada)"], "ans": 0, "exp": "the sun (unico)."}, {"q": "Complete: Let's have ___ lunch.", "ctx": "", "opts": ["(nada)", "the", "a", "an"], "ans": 0, "exp": "Refeicoes sem artigo."}, {"q": "Complete: He speaks ___ English.", "ctx": "", "opts": ["(nada)", "the", "a", "an"], "ans": 0, "exp": "Idiomas sem artigo."}, {"q": "Complete: I read ___ book you gave me.", "ctx": "", "opts": ["the", "a", "an", "(nada)"], "ans": 0, "exp": "Especifico = the."}, {"q": "Generalizacao no plural usa:", "ctx": "", "opts": ["zero artigo", "the sempre", "a/an", "this"], "ans": 0, "exp": "Sem artigo."}]$j$::jsonb),

('C1', 4023, $$Prefixos negativos$$, $$un- / dis- / mis- / over-$$, $$➖$$,
$$Prefixos mudam sentido: un- (unhappy, unfair), in-/im-/ir- (impossible, irregular), dis- (disagree, dishonest), mis- (misunderstand = entender errado), over- (overwork = trabalhar demais), under- (underestimate = subestimar).$$,
$$mis- = errado; over- = demais; under- = de menos.$$,
$j$[{"en": "I misunderstood the question.", "pt": "Entendi a pergunta errado."}, {"en": "Don't overreact.", "pt": "Nao exagere na reacao."}, {"en": "They disagreed with me.", "pt": "Discordaram de mim."}]$j$::jsonb,
$j$[{"q": "'Entender errado' =", "ctx": "", "opts": ["misunderstand", "ununderstand", "disunderstand", "overunderstand"], "ans": 0, "exp": "mis- = errado."}, {"q": "'Trabalhar demais' =", "ctx": "", "opts": ["overwork", "underwork", "miswork", "unwork"], "ans": 0, "exp": "over- = demais."}, {"q": "'Subestimar' =", "ctx": "", "opts": ["underestimate", "overestimate", "misestimate", "disestimate"], "ans": 0, "exp": "under- = de menos."}, {"q": "Oposto de 'honest':", "ctx": "", "opts": ["dishonest", "unhonest", "inhonest", "mishonest"], "ans": 0, "exp": "dishonest."}, {"q": "Oposto de 'possible':", "ctx": "", "opts": ["impossible", "unpossible", "dispossible", "inpossible"], "ans": 0, "exp": "impossible."}, {"q": "'Over-' significa:", "ctx": "", "opts": ["demais/em excesso", "de menos", "errado", "de novo"], "ans": 0, "exp": "Excesso."}]$j$::jsonb),

('C1', 4024, $$Formacao de palavras: sufixos$$, $$-tion / -ment / -ness$$, $$🔧$$,
$$Sufixos criam substantivos a partir de verbos/adjetivos: -tion (decide->decision, inform->information), -ment (develop->development), -ness (happy->happiness), -ity (able->ability), -ance (perform->performance).$$,
$$Reconhecer sufixos ajuda a deduzir a classe da palavra.$$,
$j$[{"en": "The development was fast.", "pt": "O desenvolvimento foi rapido."}, {"en": "Her happiness was clear.", "pt": "A felicidade dela era clara."}, {"en": "We value your performance.", "pt": "Valorizamos seu desempenho."}]$j$::jsonb,
$j$[{"q": "'Develop' vira substantivo:", "ctx": "", "opts": ["development", "developness", "develoption", "developity"], "ans": 0, "exp": "-ment."}, {"q": "'Happy' vira substantivo:", "ctx": "", "opts": ["happiness", "happyment", "happytion", "happity"], "ans": 0, "exp": "-ness."}, {"q": "'Decide' vira substantivo:", "ctx": "", "opts": ["decision", "decidement", "decideness", "decidity"], "ans": 0, "exp": "decision."}, {"q": "'Able' vira substantivo:", "ctx": "", "opts": ["ability", "ableness", "ablement", "abletion"], "ans": 0, "exp": "ability."}, {"q": "'-tion' costuma formar:", "ctx": "", "opts": ["substantivo", "verbo", "adjetivo", "adverbio"], "ans": 0, "exp": "Substantivo."}, {"q": "'Perform' vira substantivo:", "ctx": "", "opts": ["performance", "performment", "performness", "performtion"], "ans": 0, "exp": "performance."}]$j$::jsonb),

('C1', 4025, $$Suavizar opinioes (hedging)$$, $$It seems / I would say$$, $$🪶$$,
$$Em ingles formal/educado, suavizamos afirmacoes: 'It seems that...', 'It tends to...', 'I would say...', 'It might be...', 'to some extent', 'apparently'. Soa menos categorico e mais profissional.$$,
$$Evite afirmar 100%: prefira 'it appears' a 'it is'.$$,
$j$[{"en": "It seems to be a good idea.", "pt": "Parece ser uma boa ideia."}, {"en": "I would say it's too expensive.", "pt": "Eu diria que e caro demais."}, {"en": "This tends to happen often.", "pt": "Isso costuma acontecer com frequencia."}]$j$::jsonb,
$j$[{"q": "Suaviza 'This is wrong':", "ctx": "", "opts": ["This may not be quite right", "This is totally wrong", "Wrong!", "No way"], "ans": 0, "exp": "Hedging educado."}, {"q": "'I would say' serve para:", "ctx": "", "opts": ["dar opiniao com cautela", "ordenar", "negar tudo", "perguntar"], "ans": 0, "exp": "Opiniao suave."}, {"q": "'It tends to' indica:", "ctx": "", "opts": ["tendencia (nao regra fixa)", "certeza absoluta", "proibicao", "passado"], "ans": 0, "exp": "Tendencia."}, {"q": "'To some extent' =", "ctx": "", "opts": ["em certa medida", "totalmente", "nunca", "de novo"], "ans": 0, "exp": "Parcialmente."}, {"q": "Hedging deixa o discurso:", "ctx": "", "opts": ["mais educado/profissional", "grosseiro", "infantil", "confuso"], "ans": 0, "exp": "Educado."}, {"q": "Mais cauteloso:", "ctx": "", "opts": ["It appears to be true", "It is definitely true", "Obviously true", "100% true"], "ans": 0, "exp": "'appears' suaviza."}]$j$::jsonb),

('C1', 4026, $$E-mails formais$$, $$I am writing to / Please find$$, $$✉️$$,
$$Frases fixas de e-mail profissional: abertura 'I am writing to...', 'I hope this email finds you well'. Pedido 'I would appreciate it if...', 'Could you please...'. Anexo 'Please find attached'. Fecho 'Best regards', 'Kind regards'.$$,
$$Evite girias. Prefira 'I would appreciate' a 'I want'.$$,
$j$[{"en": "I am writing to inquire about the role.", "pt": "Escrevo para perguntar sobre a vaga."}, {"en": "Please find attached my resume.", "pt": "Segue anexo meu curriculo."}, {"en": "I look forward to your reply.", "pt": "Aguardo seu retorno."}]$j$::jsonb,
$j$[{"q": "Abertura formal:", "ctx": "", "opts": ["I am writing to...", "Hey what's up", "Yo", "Sup"], "ans": 0, "exp": "Registro formal."}, {"q": "'Segue anexo' =", "ctx": "", "opts": ["Please find attached", "Here is the thing", "Look attach", "Attach please find"], "ans": 0, "exp": "Please find attached."}, {"q": "Fecho profissional:", "ctx": "", "opts": ["Best regards", "Bye bye", "See ya", "Later"], "ans": 0, "exp": "Best regards."}, {"q": "Pedido educado:", "ctx": "", "opts": ["I would appreciate it if you could", "Do it now", "You must", "I want"], "ans": 0, "exp": "Pedido formal."}, {"q": "'Aguardo seu retorno':", "ctx": "", "opts": ["I look forward to your reply", "Answer me fast", "Reply now", "Waiting you"], "ans": 0, "exp": "look forward to."}, {"q": "Em e-mail formal, evite:", "ctx": "", "opts": ["girias e emojis", "saudacao", "assinatura", "assunto claro"], "ans": 0, "exp": "Nada de girias."}]$j$::jsonb),

('C1', 4027, $$Idioms de trabalho$$, $$ballpark figure / think outside the box$$, $$💼$$,
$$Expressoes comuns no trabalho: think outside the box (pensar diferente), ballpark figure (estimativa aproximada), touch base (dar um retorno), on the same page (em sintonia), get the ball rolling (comecar).$$,
$$Sao idiomaticas: 'touch base' nao tem a ver com beisebol literal.$$,
$j$[{"en": "Let's touch base next week.", "pt": "Vamos nos falar semana que vem."}, {"en": "We need to think outside the box.", "pt": "Precisamos pensar fora da caixa."}, {"en": "Are we on the same page?", "pt": "Estamos em sintonia?"}]$j$::jsonb,
$j$[{"q": "'Think outside the box' =", "ctx": "", "opts": ["pensar de forma criativa", "guardar em caixa", "trabalhar sozinho", "copiar"], "ans": 0, "exp": "Criatividade."}, {"q": "'Ballpark figure' =", "ctx": "", "opts": ["estimativa aproximada", "valor exato", "campo de beisebol", "erro"], "ans": 0, "exp": "Estimativa."}, {"q": "'Touch base' =", "ctx": "", "opts": ["dar um retorno/alinhar", "tocar algo", "viajar", "cancelar"], "ans": 0, "exp": "Alinhar rapidamente."}, {"q": "'On the same page' =", "ctx": "", "opts": ["em sintonia/de acordo", "na mesma pagina do livro", "atrasado", "confuso"], "ans": 0, "exp": "De acordo."}, {"q": "'Get the ball rolling' =", "ctx": "", "opts": ["comecar algo", "terminar", "jogar bola", "esperar"], "ans": 0, "exp": "Iniciar."}, {"q": "Esses idioms sao:", "ctx": "", "opts": ["comuns no ambiente de trabalho", "so em esportes", "erros", "formais demais"], "ans": 0, "exp": "Business idioms."}]$j$::jsonb),

('C1', 4028, $$Idioms de tempo e dinheiro$$, $$in the nick of time / cost a fortune$$, $$⏰$$,
$$Tempo: in the nick of time (no ultimo segundo), against the clock (contra o relogio), call it a day (encerrar). Dinheiro: cost a fortune (custar caro), tighten your belt (economizar), break the bank (gastar muito).$$,
$$Idioms nao sao literais: 'break the bank' nao e assaltar banco.$$,
$j$[{"en": "We finished in the nick of time.", "pt": "Terminamos no ultimo segundo."}, {"en": "That car cost a fortune.", "pt": "Aquele carro custou uma fortuna."}, {"en": "Let's call it a day.", "pt": "Vamos encerrar por hoje."}]$j$::jsonb,
$j$[{"q": "'In the nick of time' =", "ctx": "", "opts": ["no ultimo instante", "com atraso", "cedo demais", "nunca"], "ans": 0, "exp": "Bem em cima da hora."}, {"q": "'Cost a fortune' =", "ctx": "", "opts": ["custar muito caro", "ser barato", "ser gratis", "dar sorte"], "ans": 0, "exp": "Muito caro."}, {"q": "'Call it a day' =", "ctx": "", "opts": ["encerrar por hoje", "marcar um dia", "ligar de dia", "comecar"], "ans": 0, "exp": "Parar/encerrar."}, {"q": "'Tighten your belt' =", "ctx": "", "opts": ["economizar", "engordar", "apertar o cinto do carro", "gastar"], "ans": 0, "exp": "Cortar gastos."}, {"q": "'Against the clock' =", "ctx": "", "opts": ["com pouco tempo", "sem pressa", "no relogio", "atrasado"], "ans": 0, "exp": "Correndo contra o tempo."}, {"q": "'Break the bank' =", "ctx": "", "opts": ["gastar muito", "roubar banco", "quebrar algo", "poupar"], "ans": 0, "exp": "Gasto alto."}]$j$::jsonb),

('C1', 4029, $$Pares confusos I$$, $$affect x effect$$, $$⚠️$$,
$$Erros classicos: AFFECT (verbo: afetar) x EFFECT (substantivo: efeito). ADVICE (subst: conselho) x ADVISE (verbo: aconselhar). PRACTICE (subst) x PRACTISE (verbo, UK). LOSE (perder) x LOOSE (frouxo).$$,
$$Dica: 'The effect' (com the = substantivo). 'It affects me' (verbo).$$,
$j$[{"en": "The weather affects my mood.", "pt": "O tempo afeta meu humor."}, {"en": "It had a big effect.", "pt": "Teve um grande efeito."}, {"en": "Can you advise me?", "pt": "Pode me aconselhar?"}]$j$::jsonb,
$j$[{"q": "Verbo 'afetar':", "ctx": "", "opts": ["affect", "effect", "afect", "efect"], "ans": 0, "exp": "affect = verbo."}, {"q": "Substantivo 'efeito':", "ctx": "", "opts": ["effect", "affect", "efect", "affekt"], "ans": 0, "exp": "effect = substantivo."}, {"q": "'Me aconselhe' (verbo):", "ctx": "", "opts": ["advise me", "advice me", "advize me", "advis me"], "ans": 0, "exp": "advise = verbo."}, {"q": "'Um conselho' (substantivo):", "ctx": "", "opts": ["advice", "advise", "advize", "advis"], "ans": 0, "exp": "advice = substantivo."}, {"q": "'Perder as chaves':", "ctx": "", "opts": ["lose the keys", "loose the keys", "loos the keys", "loss the keys"], "ans": 0, "exp": "lose = perder."}, {"q": "'Frouxo/solto':", "ctx": "", "opts": ["loose", "lose", "loss", "loos"], "ans": 0, "exp": "loose = frouxo."}]$j$::jsonb),

('C1', 4030, $$Pares confusos II$$, $$raise x rise / lie x lay$$, $$⚠️$$,
$$RAISE (transitivo: levantar algo - raise your hand) x RISE (intransitivo: subir sozinho - prices rise). LIE (deitar-se: lie/lay/lain) x LAY (colocar algo: lay/laid/laid). Confundir e comum ate para nativos.$$,
$$raise precisa de objeto; rise nao. lay precisa de objeto; lie nao.$$,
$j$[{"en": "Please raise your hand.", "pt": "Por favor levante a mao."}, {"en": "The sun rises in the east.", "pt": "O sol nasce no leste."}, {"en": "I need to lie down.", "pt": "Preciso me deitar."}]$j$::jsonb,
$j$[{"q": "Levantar algo (com objeto):", "ctx": "", "opts": ["raise", "rise", "raus", "risen"], "ans": 0, "exp": "raise + objeto."}, {"q": "Subir sozinho (sem objeto):", "ctx": "", "opts": ["rise", "raise", "raises it", "rose it"], "ans": 0, "exp": "rise (intransitivo)."}, {"q": "'Me deitar':", "ctx": "", "opts": ["lie down", "lay down myself", "laid down", "lie it down"], "ans": 0, "exp": "lie = deitar-se."}, {"q": "'Colocar o livro na mesa':", "ctx": "", "opts": ["lay the book", "lie the book", "lied the book", "rise the book"], "ans": 0, "exp": "lay + objeto."}, {"q": "Passado de 'rise':", "ctx": "", "opts": ["rose", "raised", "risen", "rised"], "ans": 0, "exp": "rise-rose-risen."}, {"q": "'Raise' exige:", "ctx": "", "opts": ["um objeto", "nenhum objeto", "gerundio", "preposicao"], "ans": 0, "exp": "Transitivo."}]$j$::jsonb);

commit;
