-- ============================================================================
-- SpeakUp — Lote C2 (12 lições avançadas inéditas)
-- Nível C2 estava vazio na tabela "licoes". Estes tópicos NÃO duplicam os ~260
-- já existentes. Resposta correta marcada por "ans" (o app embaralha as opções).
-- Como aplicar: Supabase -> SQL Editor -> cole tudo -> RUN. Seguro rodar 1x.
-- (O app já usa o campo "nivel" para o nível CEFR, então não precisa mexer no código.)
-- ============================================================================

insert into licoes (nivel, ordem, titulo, sub, icon, explicacao, dica, exemplos, questoes) values

('C2', 1111, $$Binômios fixos$$, $$back and forth, sooner or later$$, $$🔁$$,
$$Binômios são pares de palavras em ordem fixa ligados por "and" ou "or". Invertê-los soa estranho para nativos.$$,
$$A ordem é fixa: dizemos "salt and pepper", nunca "pepper and salt".$$,
$j$[{"en":"They walked back and forth nervously.","pt":"Andaram de um lado para o outro, nervosos."},{"en":"Sooner or later, you will understand.","pt":"Mais cedo ou mais tarde você vai entender."},{"en":"By and large, the plan worked.","pt":"De modo geral, o plano funcionou."}]$j$::jsonb,
$j$[{"q":"Complete: salt and ___","ctx":"","opts":["pepper","sugar","water","bread"],"ans":0,"exp":"salt and pepper (ordem fixa)."},{"q":"'Sooner or later' significa:","ctx":"","opts":["mais cedo ou mais tarde","agora mesmo","nunca","talvez"],"ans":0,"exp":"Cedo ou tarde."},{"q":"'By and large' =","ctx":"","opts":["de modo geral","com força","aos poucos","de repente"],"ans":0,"exp":"Em geral."},{"q":"Binômio para 'sãos e salvos':","ctx":"","opts":["safe and sound","sound and safe","safe or sound","sound and safe"],"ans":0,"exp":"safe and sound."},{"q":"'Pros and cons' =","ctx":"","opts":["prós e contras","idas e vindas","altos e baixos","ganhos e perdas"],"ans":0,"exp":"Vantagens e desvantagens."},{"q":"O que define um binômio fixo?","ctx":"","opts":["a ordem das palavras é fixa","pode inverter livremente","tem três palavras","é sempre formal"],"ans":0,"exp":"Ordem consagrada."}]$j$::jsonb),

('C2', 1112, $$Idioms de negócios$$, $$ballpark figure, touch base$$, $$💼$$,
$$O inglês corporativo é cheio de expressões idiomáticas. Reconhecê-las é essencial em reuniões internacionais.$$,
$$"Touch base" = dar um alô / alinhar rapidamente. "Ballpark figure" = valor aproximado.$$,
$j$[{"en":"Let us touch base next week.","pt":"Vamos nos alinhar na próxima semana."},{"en":"Can you give me a ballpark figure?","pt":"Pode me dar um valor aproximado?"},{"en":"We need to think outside the box.","pt":"Precisamos pensar de forma criativa."}]$j$::jsonb,
$j$[{"q":"'Touch base' significa:","ctx":"","opts":["alinhar/dar um alô","tocar a base","começar do zero","assinar contrato"],"ans":0,"exp":"Contato rápido."},{"q":"'Ballpark figure' =","ctx":"","opts":["valor aproximado","número exato","lucro final","meta anual"],"ans":0,"exp":"Estimativa."},{"q":"'To be on the same page' =","ctx":"","opts":["estar de acordo","ler o mesmo livro","na mesma sala","no mesmo nível"],"ans":0,"exp":"Mesmo entendimento."},{"q":"'The bottom line' =","ctx":"","opts":["o ponto principal","a última linha","o rodapé","o prejuízo"],"ans":0,"exp":"O que importa."},{"q":"'To get the ball rolling' =","ctx":"","opts":["dar início","encerrar","atrasar","cancelar"],"ans":0,"exp":"Começar."},{"q":"'A win-win situation' =","ctx":"","opts":["bom para os dois lados","vitória difícil","sem solução","jogo duplo"],"ans":0,"exp":"Todos ganham."}]$j$::jsonb),

('C2', 1113, $$Intensificadores e atenuadores$$, $$utterly, fairly, somewhat$$, $$📈$$,
$$Advérbios de grau ajustam a força de um adjetivo: utterly/absolutely (muito forte), fairly/somewhat (moderado), slightly (leve).$$,
$$"Utterly" e "absolutely" combinam com adjetivos extremos: "absolutely exhausted", não "absolutely tired".$$,
$j$[{"en":"The film was utterly brilliant.","pt":"O filme foi absolutamente brilhante."},{"en":"I am somewhat tired today.","pt":"Estou um tanto cansado hoje."},{"en":"It is fairly common here.","pt":"É bastante comum por aqui."}]$j$::jsonb,
$j$[{"q":"'Utterly' indica grau:","ctx":"","opts":["muito forte","leve","médio","nenhum"],"ans":0,"exp":"Intensificador forte."},{"q":"'Somewhat' significa:","ctx":"","opts":["um tanto","totalmente","jamais","extremamente"],"ans":0,"exp":"Moderado."},{"q":"Combina com 'exhausted':","ctx":"","opts":["absolutely","very","fairly","a bit"],"ans":0,"exp":"Adjetivo extremo + absolutely."},{"q":"'Slightly' =","ctx":"","opts":["levemente","muito","sempre","nunca"],"ans":0,"exp":"Grau leve."},{"q":"Atenuador (suaviza):","ctx":"","opts":["rather","utterly","absolutely","completely"],"ans":0,"exp":"'Rather' modera."},{"q":"'Quite' diante de extremo soa:","ctx":"","opts":["estranho (use absolutely)","perfeito","formal","grosseiro"],"ans":0,"exp":"Extremos pedem absolutely."}]$j$::jsonb),

('C2', 1114, $$Linguagem de manchetes$$, $$headlines: PM vows, talks set$$, $$📰$$,
$$Manchetes de jornal usam gramática própria: omitem artigos, usam presente para o passado e infinitivo para o futuro.$$,
$$"Mayor to visit Brazil" = O prefeito VAI visitar. "to + verbo" = futuro em manchetes.$$,
$j$[{"en":"President vows to cut taxes.","pt":"Presidente promete cortar impostos."},{"en":"Talks set for Monday.","pt":"Negociações marcadas para segunda."},{"en":"Star to return next season.","pt":"Astro vai voltar na próxima temporada."}]$j$::jsonb,
$j$[{"q":"Em manchetes, 'to + verbo' indica:","ctx":"","opts":["futuro","passado","ordem","dúvida"],"ans":0,"exp":"Futuro."},{"q":"Manchetes costumam omitir:","ctx":"","opts":["artigos (a, the)","verbos","substantivos","nomes"],"ans":0,"exp":"Economia de espaço."},{"q":"'PM vows reform' usa o presente para:","ctx":"","opts":["um fato recente (passado)","o futuro","um hábito","uma ordem"],"ans":0,"exp":"Presente = passado jornalístico."},{"q":"'Quake hits city' =","ctx":"","opts":["Terremoto atingiu a cidade","Vai atingir","Pode atingir","Atinge sempre"],"ans":0,"exp":"Presente por passado."},{"q":"'Jobs report due today' — 'due' =","ctx":"","opts":["previsto/esperado","atrasado","cancelado","devido a"],"ans":0,"exp":"Esperado para hoje."},{"q":"O estilo de manchete é:","ctx":"","opts":["condensado","formal e completo","coloquial","poético"],"ans":0,"exp":"Telegráfico."}]$j$::jsonb),

('C2', 1115, $$Expressões latinas no inglês$$, $$per se, vice versa, etc.$$, $$🏛️$$,
$$O inglês formal e acadêmico usa termos latinos: per se (em si), vice versa, etc. (e assim por diante), i.e. (isto é), e.g. (por exemplo).$$,
$$"i.e." esclarece (isto é); "e.g." dá exemplos (por exemplo). Não confunda os dois.$$,
$j$[{"en":"The plan is not bad per se.","pt":"O plano não é ruim em si."},{"en":"She helps him and vice versa.","pt":"Ela o ajuda e vice-versa."},{"en":"Bring fruit, e.g. apples.","pt":"Traga frutas, por exemplo maçãs."}]$j$::jsonb,
$j$[{"q":"'per se' significa:","ctx":"","opts":["em si mesmo","por favor","com certeza","de novo"],"ans":0,"exp":"Em si."},{"q":"'i.e.' =","ctx":"","opts":["isto é","por exemplo","e outros","ou seja não"],"ans":0,"exp":"id est = isto é."},{"q":"'e.g.' =","ctx":"","opts":["por exemplo","isto é","e assim por diante","sem dúvida"],"ans":0,"exp":"exempli gratia."},{"q":"'etc.' =","ctx":"","opts":["e assim por diante","isto é","por exemplo","com licença"],"ans":0,"exp":"et cetera."},{"q":"'vice versa' =","ctx":"","opts":["o contrário também","duas vezes","ao contrário errado","em vão"],"ans":0,"exp":"Reciprocamente."},{"q":"'ad hoc' =","ctx":"","opts":["feito para um fim específico","muito antigo","de graça","ilegal"],"ans":0,"exp":"Para um propósito."}]$j$::jsonb),

('C2', 1116, $$Phrasal verbs de três partes$$, $$look forward to, put up with$$, $$🔧$$,
$$Phrasal verbs de três partes (verbo + advérbio + preposição) nunca se separam e têm sentido idiomático.$$,
$$"Look forward to" é seguido de substantivo ou verbo -ing: "I look forward to seeing you."$$,
$j$[{"en":"I look forward to your reply.","pt":"Aguardo ansiosamente sua resposta."},{"en":"She came up with a plan.","pt":"Ela bolou um plano."},{"en":"We ran out of time.","pt":"Ficamos sem tempo."}]$j$::jsonb,
$j$[{"q":"'look forward to' é seguido de:","ctx":"","opts":["substantivo ou -ing","infinitivo com to","passado","adjetivo"],"ans":0,"exp":"to + -ing aqui é preposição."},{"q":"'come up with' =","ctx":"","opts":["bolar/inventar","subir","encontrar","desistir"],"ans":0,"exp":"Inventar."},{"q":"'run out of' =","ctx":"","opts":["ficar sem","correr para fora","esgotar de propósito","sair correndo"],"ans":0,"exp":"Acabar (estoque)."},{"q":"'put up with' =","ctx":"","opts":["tolerar","hospedar","levantar","construir"],"ans":0,"exp":"Suportar."},{"q":"'get along with' =","ctx":"","opts":["se dar bem com","ir junto","seguir","concordar"],"ans":0,"exp":"Boa relação."},{"q":"Phrasal de 3 partes podem separar as partículas?","ctx":"","opts":["não","sempre","às vezes","só no passado"],"ans":0,"exp":"São inseparáveis."}]$j$::jsonb),

('C2', 1117, $$Coloquialismos e fala natural$$, $$gonna, wanna, kinda$$, $$🗣️$$,
$$Na fala rápida, nativos reduzem palavras: going to → gonna, want to → wanna, kind of → kinda. Comuns ao ouvir, mas evite na escrita formal.$$,
$$Entenda ao ouvir, mas escreva a forma completa em textos formais.$$,
$j$[{"en":"I am gonna call you later.","pt":"Vou te ligar mais tarde."},{"en":"Do you wanna come?","pt":"Você quer vir?"},{"en":"It is kinda cold.","pt":"Está meio frio."}]$j$::jsonb,
$j$[{"q":"'gonna' = ","ctx":"","opts":["going to","got to","gone","good"],"ans":0,"exp":"going to."},{"q":"'wanna' =","ctx":"","opts":["want to","want a","won't","wander"],"ans":0,"exp":"want to."},{"q":"'kinda' =","ctx":"","opts":["kind of","kind","kid","kinder"],"ans":0,"exp":"kind of = meio."},{"q":"Essas formas são adequadas em:","ctx":"","opts":["fala informal","contratos","redações","e-mails formais"],"ans":0,"exp":"Só informal."},{"q":"'gotta' =","ctx":"","opts":["got to (ter que)","get a","gotcha","gutter"],"ans":0,"exp":"have got to."},{"q":"'lemme' =","ctx":"","opts":["let me","leave me","lemon","limit"],"ans":0,"exp":"let me."}]$j$::jsonb),

('C2', 1118, $$Marcadores de coesão textual$$, $$moreover, nevertheless, thereby$$, $$🔗$$,
$$Conectores formais dão fluidez a textos avançados: moreover (além disso), nevertheless (ainda assim), thus/thereby (assim), whereas (ao passo que).$$,
$$"Nevertheless" admite um contraste apesar do que foi dito; "moreover" acrescenta um argumento.$$,
$j$[{"en":"The data is old; moreover, it is incomplete.","pt":"Os dados são antigos; além disso, incompletos."},{"en":"It rained; nevertheless, we went.","pt":"Choveu; ainda assim, fomos."},{"en":"He saved money, whereas she spent.","pt":"Ele economizou, ao passo que ela gastou."}]$j$::jsonb,
$j$[{"q":"'moreover' =","ctx":"","opts":["além disso","no entanto","portanto","por exemplo"],"ans":0,"exp":"Adiciona."},{"q":"'nevertheless' =","ctx":"","opts":["ainda assim","além disso","assim","porque"],"ans":0,"exp":"Contraste."},{"q":"'whereas' =","ctx":"","opts":["ao passo que","porque","então","embora não"],"ans":0,"exp":"Contraste paralelo."},{"q":"'thus' =","ctx":"","opts":["assim/portanto","além disso","mas","quando"],"ans":0,"exp":"Consequência."},{"q":"'in contrast' indica:","ctx":"","opts":["oposição","adição","causa","tempo"],"ans":0,"exp":"Contraste."},{"q":"Esses marcadores são típicos de:","ctx":"","opts":["texto formal/acadêmico","conversa casual","gírias","manchetes"],"ans":0,"exp":"Registro formal."}]$j$::jsonb),

('C2', 1119, $$Linguagem inclusiva e neutra$$, $$they, chairperson, staff$$, $$🤝$$,
$$O inglês moderno prefere termos neutros de gênero: chairperson (não chairman), firefighter (não fireman), e "they" singular para pessoa indefinida.$$,
$$"If a student needs help, they should ask." — "they" singular é aceito e inclusivo.$$,
$j$[{"en":"Everyone should bring their own laptop.","pt":"Cada um deve trazer seu próprio laptop."},{"en":"She is a firefighter.","pt":"Ela é bombeira."},{"en":"The chairperson opened the meeting.","pt":"O(a) presidente abriu a reunião."}]$j$::jsonb,
$j$[{"q":"Forma neutra de 'chairman':","ctx":"","opts":["chairperson","chairwoman","chairboy","chairmate"],"ans":0,"exp":"Neutro."},{"q":"Neutro de 'policeman':","ctx":"","opts":["police officer","policeperson","copman","guard"],"ans":0,"exp":"police officer."},{"q":"'they' singular serve para:","ctx":"","opts":["pessoa indefinida","apenas plural","só objetos","só formal"],"ans":0,"exp":"Inclusivo singular."},{"q":"Neutro de 'stewardess':","ctx":"","opts":["flight attendant","air lady","stewardman","hostess"],"ans":0,"exp":"flight attendant."},{"q":"'mankind' pode virar:","ctx":"","opts":["humanity","manhood","menkind","peoplekind"],"ans":0,"exp":"humanity."},{"q":"Linguagem inclusiva busca:","ctx":"","opts":["evitar marca de gênero desnecessária","ser informal","encurtar frases","soar antiga"],"ans":0,"exp":"Neutralidade."}]$j$::jsonb),

('C2', 1120, $$Vocabulário britânico vs americano$$, $$lift/elevator, flat/apartment$$, $$🌍$$,
$$Britânico e americano diferem em vocabulário: lift/elevator, flat/apartment, lorry/truck, queue/line, holiday/vacation.$$,
$$Mesmo idioma, palavras diferentes. Saiba reconhecer as duas variantes.$$,
$j$[{"en":"I live in a flat. (UK)","pt":"Moro num apartamento."},{"en":"Take the elevator. (US)","pt":"Pegue o elevador."},{"en":"We waited in the queue. (UK)","pt":"Esperamos na fila."}]$j$::jsonb,
$j$[{"q":"'lift' (UK) = ___ (US)","ctx":"","opts":["elevator","stairs","escalator","ramp"],"ans":0,"exp":"elevator."},{"q":"'flat' (UK) = ___ (US)","ctx":"","opts":["apartment","house","floor","room"],"ans":0,"exp":"apartment."},{"q":"'lorry' (UK) = ___ (US)","ctx":"","opts":["truck","car","bus","van"],"ans":0,"exp":"truck."},{"q":"'queue' (UK) = ___ (US)","ctx":"","opts":["line","row","tail","file"],"ans":0,"exp":"line."},{"q":"'holiday' (UK) frequentemente = ___ (US)","ctx":"","opts":["vacation","feriado só","weekend","day off"],"ans":0,"exp":"vacation."},{"q":"'petrol' (UK) = ___ (US)","ctx":"","opts":["gas","oil","fuel tank","diesel"],"ans":0,"exp":"gas(oline)."}]$j$::jsonb),

('C2', 1121, $$Aliteração e jogos de palavras$$, $$puns, tongue twisters$$, $$🎭$$,
$$Falantes avançados apreciam trocadilhos (puns), aliteração (sons repetidos) e jogos de palavras — comuns em propaganda, humor e títulos.$$,
$$Trocadilhos exploram palavras com sons iguais e sentidos diferentes (ex.: "time flies").$$,
$j$[{"en":"Time flies like an arrow.","pt":"O tempo voa como uma flecha. (trocadilho)"},{"en":"She sells seashells by the seashore.","pt":"Trava-língua clássico."},{"en":"Big brands build buzz.","pt":"Grandes marcas geram burburinho. (aliteração)"}]$j$::jsonb,
$j$[{"q":"Aliteração é a repetição de:","ctx":"","opts":["sons iniciais","significados","frases","rimas finais"],"ans":0,"exp":"Sons iniciais."},{"q":"Um 'pun' é:","ctx":"","opts":["um trocadilho","uma rima","um erro","um sotaque"],"ans":0,"exp":"Jogo de duplo sentido."},{"q":"'Tongue twister' =","ctx":"","opts":["trava-língua","gíria","provérbio","insulto"],"ans":0,"exp":"Difícil de pronunciar."},{"q":"Trocadilhos são comuns em:","ctx":"","opts":["propaganda e humor","contratos","provas","receitas"],"ans":0,"exp":"Publicidade/humor."},{"q":"'Letter' tem dois sentidos:","ctx":"","opts":["carta e letra","só carta","só letra","número"],"ans":0,"exp":"Base de muitos puns."},{"q":"Reconhecer jogos de palavras exige:","ctx":"","opts":["vocabulário e contexto","apenas gramática","tradução literal","só áudio"],"ans":0,"exp":"Nuance avançada."}]$j$::jsonb),

('C2', 1122, $$Polidez e indireção$$, $$I was wondering if...$$, $$🤲$$,
$$Em inglês, pedidos diretos podem soar rudes. Falantes avançados suavizam com estruturas indiretas: "I was wondering if...", "Would you mind...", "Could you possibly...".$$,
$$Quanto mais indireto e condicional, mais educado: "Would you mind opening the window?"$$,
$j$[{"en":"I was wondering if you could help.","pt":"Eu queria saber se você poderia ajudar."},{"en":"Would you mind closing the door?","pt":"Você se importaria de fechar a porta?"},{"en":"Could you possibly call back later?","pt":"Será que você poderia ligar mais tarde?"}]$j$::jsonb,
$j$[{"q":"Mais educado:","ctx":"","opts":["Would you mind helping?","Help me.","I need help now.","Do it."],"ans":0,"exp":"Indireto = educado."},{"q":"'I was wondering if...' serve para:","ctx":"","opts":["pedir com delicadeza","reclamar","ordenar","recusar"],"ans":0,"exp":"Pedido suave."},{"q":"Após 'Would you mind' usa-se:","ctx":"","opts":["verbo -ing","infinitivo","passado","adjetivo"],"ans":0,"exp":"mind + -ing."},{"q":"'Could you possibly...' soa:","ctx":"","opts":["bem educado","grosseiro","informal demais","arcaico"],"ans":0,"exp":"Muito cortês."},{"q":"Indireção em pedidos serve para:","ctx":"","opts":["soar polido","ganhar tempo","confundir","encurtar"],"ans":0,"exp":"Polidez."},{"q":"Resposta educada a 'Would you mind...?' (aceitando):","ctx":"","opts":["Not at all.","Yes, I mind.","No way.","Of course not, never."],"ans":0,"exp":"'Not at all' = sem problema."}]$j$::jsonb);
