-- ============================================================================
-- Vonai — MIGRAÇÃO 18/08/2026: freemium de verdade + trial de 7 dias
-- Cole no Supabase -> SQL Editor -> RUN. Idempotente: seguro rodar mais de uma vez.
--
-- O que mudou no produto (ver MONETIZACAO.md):
--   - Trial passa de 2 para 7 dias.
--   - Depois do trial o aluno NÃO é trancado: cai no plano grátis (10 msgs/dia com o
--     professor, 3 simulações/dia, 3 lições/dia). O servidor parou de responder 402.
--   - Webhook da Kiwify casa o pagamento pelo user_id (s1 do link do checkout) além do
--     e-mail; o que não casa vai para pagamentos_pendentes e o dono libera em /admin.
--   - E-mails de ciclo de vida (T-24h do trial, T+1 e T+4 depois) com trava de idempotência.
-- ============================================================================
begin;

-- ---------------------------------------------------------------------------
-- (a) TRIAL DE 7 DIAS — dois lugares decidem a duração, e os dois precisam mudar:
--
--   1) handle_new_user: trigger de auth.users que cria o profile no cadastro.
--   2) protege_profiles (protecao-custos.sql): trigger BEFORE INSERT/UPDATE em profiles
--      que, para qualquer chamada que não seja service_role, IGNORA o trial_expira que
--      veio e grava now() + 2 days. Como o handle_new_user roda no contexto do auth (sem
--      JWT de service_role), é ESTE trigger que dá a palavra final — mudar só o
--      handle_new_user deixaria o trial em 2 dias sem ninguém entender por quê.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, nome, plano, ativo, trial_expira)
  values (new.id, new.email,
          -- Nome opcional no cadastro (AuthForm) e no login com Google: cai na parte antes do @.
          coalesce(nullif(new.raw_user_meta_data->>'nome', ''),
                   nullif(new.raw_user_meta_data->>'full_name', ''),
                   nullif(new.raw_user_meta_data->>'name', ''),
                   split_part(new.email, '@', 1)),
          'free', true, now() + interval '7 days')
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function protege_profiles()
returns trigger
language plpgsql
as $$
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    if tg_op = 'UPDATE' then
      new.trial_expira := old.trial_expira;
      new.plano := old.plano;
    else
      -- Cadastro: o trial de 7 dias é definido AQUI, não pelo app (era 2 dias até 18/08/2026).
      new.trial_expira := now() + interval '7 days';
      new.plano := 'free';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists trg_protege_profiles on profiles;
create trigger trg_protege_profiles
  before insert or update on profiles
  for each row execute function protege_profiles();

-- ---------------------------------------------------------------------------
-- (b) PAGAMENTOS PENDENTES — o webhook insere { email, tipo, payload } quando nenhuma
-- conta casa (nem por s1, nem por e-mail). Colunas batem com o insert do
-- app/api/kiwify-webhook/route.ts. resolvido_em é nova: o /admin marca quando o dono
-- libera na mão (a rota tolera a coluna ausente, mas sem ela não fica a data).
-- ---------------------------------------------------------------------------
create table if not exists pagamentos_pendentes (
  id bigint generated by default as identity primary key,
  email text,
  tipo text,
  payload jsonb,
  resolvido boolean not null default false,
  created_at timestamptz not null default now()
);
alter table pagamentos_pendentes add column if not exists resolvido_em timestamptz;
create index if not exists pagamentos_pendentes_created_at_idx on pagamentos_pendentes (created_at desc);
-- Sem policies: só o service_role (webhook e /api/admin/pendentes) lê e escreve.
alter table pagamentos_pendentes enable row level security;

-- Diário de bordo do webhook (webhook_recebidos.sql) ganha o s1 do checkout, para
-- conferir se a Kiwify está devolvendo o user_id que o app manda no link.
-- Só se a tabela já existir (webhook_recebidos.sql pode não ter sido aplicado ainda).
do $$ begin
  if to_regclass('public.webhook_recebidos') is not null then
    alter table webhook_recebidos add column if not exists s1 text;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- (c) E-MAILS DO CICLO DE VIDA — o cron /api/send-reminders roda 2x/dia; sem um registro
-- do que já foi mandado, o "seu teste acaba amanhã" iria duas vezes. JSON { chave: dia }:
--   trial_t24, pos_trial_1, pos_trial_2 (1x cada, por pessoa) e winback (último envio,
--   espaçamento mínimo de 3 dias). A rota funciona sem a coluna (cai para 1x/dia à noite),
--   mas só com ela a idempotência é garantida.
-- ---------------------------------------------------------------------------
alter table progresso add column if not exists emails_enviados jsonb not null default '{}'::jsonb;

commit;

-- ============================================================================
-- (d) OPCIONAL — REATIVAÇÃO DOS ALUNOS TRANCADOS NO PAYWALL DURO. Rodar UMA vez, na mão,
-- JUNTO com um e-mail avisando ("voltamos com 7 dias de Premium para você"), senão os
-- 7 dias passam em branco. Dá 7 dias novos a quem já teve o trial (de 2 dias) vencido e
-- não é assinante. Não mexe em quem paga nem em quem ainda está no trial.
-- Conferir antes quantos são:
--   select count(*) from profiles p
--    where p.trial_expira < now()
--      and p.id not in (select user_id from progresso where is_premium);
-- Descomente para aplicar:
-- update profiles
--    set trial_expira = now() + interval '7 days'
--  where trial_expira < now()
--    and id not in (select user_id from progresso where is_premium);
-- ============================================================================

-- ============================================================================
-- (e) OPCIONAL — RANKING SEMANAL EXPOSTO PARA ANÔNIMOS. _APLICAR_PENDENTES.sql:22-27 criou
-- a view ranking_semanal com security_invoker = off e `grant select ... to anon`: qualquer
-- pessoa SEM login consegue listar nome + XP de todos os alunos (dado pessoal, LGPD).
-- O app só consulta a view LOGADO (app/app/page.tsx, supabase.from('ranking_semanal')),
-- então `authenticated` basta. Antes de rodar, conferir:
--   1) que a view existe:  select * from pg_views where viewname = 'ranking_semanal';
--   2) que o grant existe: select grantee, privilege_type from information_schema.role_table_grants
--                          where table_name = 'ranking_semanal';
--   3) que nenhuma página pública (landing, /teste-de-nivel) usa a view sem login.
-- Descomente para aplicar:
-- revoke select on ranking_semanal from anon;
-- ============================================================================
