-- ============================================================================
-- Vonai — Stripe com cartão na entrada (30/08/2026).
-- Cole no Supabase -> SQL Editor -> RUN. Roda em qualquer ordem, é idempotente.
--
-- Por que existe: até aqui o aluno usava 3 dias, o app trancava e ele precisava voltar
-- sozinho para pagar. Ninguém fazia isso — 149 contas, zero assinantes. Com o Stripe o
-- cartão entra no cadastro e a 1ª cobrança acontece sozinha no fim do teste.
-- ============================================================================

-- Liga a conta do aluno ao cliente e à assinatura no Stripe. É por aqui que as
-- renovações, cancelamentos e reembolsos acham o dono da conta.
alter table public.progresso add column if not exists stripe_customer_id text;
alter table public.progresso add column if not exists stripe_subscription_id text;
-- trialing | active | past_due | canceled | unpaid | reembolsado
alter table public.progresso add column if not exists stripe_status text;

-- O webhook busca por customer_id em toda renovação: sem índice isso vira varredura
-- de tabela inteira a cada evento.
create index if not exists progresso_stripe_customer_idx on public.progresso (stripe_customer_id);
create index if not exists progresso_stripe_sub_idx on public.progresso (stripe_subscription_id);

-- Diário de bordo dos webhooks (já existe se o de 18/08 rodou; aqui é rede de segurança).
create table if not exists public.webhook_recebidos (
  id bigint generated by default as identity primary key,
  origem text,
  autorizado boolean,
  tem_segredo boolean,
  tem_token boolean,
  tem_assinatura boolean,
  tipo text,
  bytes int,
  s1 text,
  created_at timestamptz not null default now()
);
alter table public.webhook_recebidos enable row level security;

-- Conferência rápida depois de rodar:
--   select column_name from information_schema.columns
--   where table_name = 'progresso' and column_name like 'stripe%';
-- Deve listar stripe_customer_id, stripe_status e stripe_subscription_id.
