-- Aplicar no SQL Editor do Supabase ANTES do deploy do webhook novo (29/07/2026).

-- Fim do ciclo pago da assinatura Kiwify. NULL = sem prazo (trial gerencia por profiles.trial_expira;
-- iOS gerencia pelo evento EXPIRATION do RevenueCat). O acesso vale enquanto
-- is_premium = true E (premium_expira IS NULL OU premium_expira > now()).
alter table progresso add column if not exists premium_expira timestamptz;

-- Pagamentos da Kiwify que não casaram com nenhuma conta (e-mail diferente do cadastro):
-- ficam aqui para reconciliação manual em vez de sumir em silêncio.
create table if not exists pagamentos_pendentes (
  id bigint generated by default as identity primary key,
  email text,
  tipo text,
  payload jsonb,
  resolvido boolean not null default false,
  created_at timestamptz not null default now()
);

-- Sem policies: só o service_role (webhooks) lê e escreve.
alter table pagamentos_pendentes enable row level security;
